### ISSUE TITLE
Investigate query.rq file for newcastle-pilot

### ISSUE THREAD

**Issue by matt-wallis** [p6data-coop/ise-linked-open-data#101]
This looks wrong:
```
grep dotcoop www/services/newcastle-pilot/query.rq
PREFIX : <https://w3id.solidarityeconomy.coop/dotcoop/>
```
Why is `dotcoop` in there?

This begs the questions:
- When is this file created?
- Is it used by the map-app? Or is it just for testing?
- If it's used at all, even for testing, then it needs to be fixed.

**Comment by joebillings** [comment]
Copy/paste bug
