### ISSUE TITLE
Finalise URIs for newcastle pilot

### ISSUE THREAD

**Issue by matt-wallis** [p6data-coop/ise-linked-open-data#102]
This requires a couple of things:
- make decision what they should look like
- if using w3id.org (recommended), then submit the appropriate pull request

At the time of writing, we're using our fork of `w3id.org` to do the redirections, so the UrIs start like this:
```
https://w3id.solidarityeconomy.coop/sea-lod/newcastle-pilot/
```

At some point, we need to drop the use of our fork:
```
https://w3id.org/sea-lod/newcastle-pilot/
```
And maybe drop the word pilot:
```
https://w3id.org/sea-lod/newbridge/
```
The remainder of the URI is formed by removing non-alphanumeric characters from the name of the initiative.

Note that the fork of w3id.org is at `matt@ise-0:/var/www/html/w3id.org`. 
There is a branch called newcastle-pilot.

- [ ] A pull request will be needed in order to move over to the URIs based at `w3id.org`.

**Comment by joebillings** [comment]
w3id.org/sea-lod/{project}/{date-created?}/{uid or name-as-alphanumeric}
