### ISSUE TITLE
map-app should receive data as RDF

### ISSUE THREAD

**Issue by matt-wallis** [p6data-coop/ise-linked-open-data#103]
Currently, the web server makes the SPARQL query to the triple store using [getdata_using_sparql.php](https://github.com/SolidarityEconomyAssociation/open-data-and-maps/blob/master/map-app/www/services/getdata_using_sparql.php). It requests a json response:
```
        $headers = array(
                "Accept: application/json"
        );
```
The `json` is then converted into simple json with the following keys for each initiative:
```
$keys = array("name", "uri", "within", "lat", "lng", "www", "regorg");
```

It would be more flexible if RDF were sent straight through to the map-app. This is one way to fix #38, but it has other benefits too:
- removes a layer of code (the translation done by `getdata_using_sparql.php`)
- deals with language translation at the browser (so user can change languages without needed to refetch all the data
- if we include RDF for essglobal, for example, then we can also use labels from the vocabulary. (Or is there a better way of doing this?

The obvious RDF serialization format for a javascript app to consume is `JSON-LD`.
To parse json-ld in the browser, https://github.com/digitalbazaar/jsonld.js/ looks worth investigation. Note the use of 'contexts' and 'compacting'.

References: 
- https://www.w3.org/TR/json-ld/
- https://www.w3.org/TR/sparql11-results-json/
- https://json-ld.org/spec/latest/json-ld/

**Comment by matt-wallis** [comment]
> The `json-ld` is then converted into simple json with the following keys for each initiative:

On looking more closely, I'm wondering if we are getting JSON-LD from the SPARQL query, or just plain JSON. Hmm.

Here's an example of a  SPARQL query used by [getdata_using_sparql.php](https://github.com/SolidarityEconomyAssociation/open-data-and-maps/blob/master/map-app/www/services/getdata_using_sparql.php):
```
curl -i -H "Accept: application/json"  --data default-graph-uri=https://w3id.solidarityeconomy.coop/dotcoop/ --data-urlencode query@generated-data/experimental/sparql/query.rq http://store1.solidarityeconomy.coop:8890/sparql
```

**Comment by matt-wallis** [comment]
Very useful comment [on stackoverflow](https://stackoverflow.com/a/27033528/685715) clarifying the use of JSON-LD, and pointing out that it is not what we should expect from a SPARQL SELECT query, which is what we have (e.g. see [dotcoop sparql query](https://github.com/SolidarityEconomyAssociation/open-data-and-maps/blob/master/map-app/www/services/dotcoop/query.rq)).

The JSON we get from our `SELECT` query is specified by https://www.w3.org/TR/sparql11-results-json/

Looking at [W3C SPARQL Query Language for RDF, CONSTRUCT](https://www.w3.org/TR/rdf-sparql-query/#accessingRdfGraphs), we can use `CONSTRUCT` instead of `SELECT`, for example:
```
CONSTRUCT { ?s ?p ?o } WHERE { GRAPH <https://w3id.solidarityeconomy.coop/dotcoop/> { ?s ?p ?o } . }
```
and a query like this:
```
$ curl -i -H "Accept: application/json"   --data-urlencode query='CONSTRUCT { ?s ?p ?o } WHERE { GRAPH <https://w3id.solidarityeconomy.coop/dotcoop/> { ?s ?p ?o } . }' http://store1.solidarityeconomy.coop:8890/sparql
```
This dumps out all of the triples from that named graph, but I don't think this is JSON-LD. Need to check.

Looking at the results from this `SPARQL CONSTRUCT` query, there are some clear benefits:
- It contains "everything", including the specification of the essglobal URIs that we are using. This means that we can use the correct labels from the vocabulary when presenting information to the user of the map-app. 
However, the fact that is includes essglobal is down to us loading essglobal into every Named Graph. That's a practice we probably need to stop! See #105

**Comment by joebillings** [comment]
https://www.npmjs.com/package/sparqljs
