### ISSUE TITLE
Upgrade to latest version of Virtuoso 

### ISSUE THREAD

**Issue by matt-wallis** [p6data-coop/ise-linked-open-data#104]
We are using Version 06.01.3127, an old unsupported version. We should be using the latest [Virtuoso Open-Source Edition](http://vos.openlinksw.com/owiki/wiki/VOS/).

Rather than attempt to upgrade the existing server, it is probably safer to set up a new server with the new version of Viruoso. In doing so, we should update [the documentation](https://github.com/SolidarityEconomyAssociation/open-data-and-maps/wiki/OntoWiki-Installation-Ubuntu), and probably drop the bits about OntoWiki, which we are not using.

**Comment by matt-wallis** [comment]
@joebillings Is the newer Scaleway server running a recent version of Virtuoso? If so, I think this can be closed.

**Comment by joebillings** [comment]
I used the same version as the other server to void any issues so will leave this open. I'll use [Docker](https://www.docker.com/) which will allow us to create containerised instances of everything. We'll then be able to do everything on a single server. When the time arises, we'll also be able to send containers to partners so they can easily create the exact same environment on their own server.

**Comment by ColmMassey** [comment]
Can we close this @wu-lee ? If not, no implied recommendation to do this anytime soon.

**Comment by wu-lee** [comment]
I think so, we're on the open source version 6.1, and this is the current latest available on Ubuntu Xenial.  (Possibly we might want to go to a more recent version of Ubuntu tho.)

**Comment by ColmMassey** [comment]
It does seem that all the virtuoso development has not been ported to work on our Ubuntu distro. How much effort is it to change distro?

**Comment by wu-lee** [comment]
Upgrading to a newer Ubuntu: not too bad. Except these also don't seem to have a newer version of Virtuoso than 6.1

https://launchpad.net/ubuntu/+source/virtuoso-opensource

Switching to another distro like Arch Linux: more risky, without know-how. I've a bit of experience with Arch, quite a lot with Red Hat/CentOS/Fedora. But the former only has a user-contributed package: 

https://aur.archlinux.org/packages/virtuoso/

And the latter don't seem to have any new versions of virtuoso either:

https://rpmfind.net/linux/rpm2html/search.php?query=virtuoso-opensource

See https://github.com/SolidarityEconomyAssociation/open-data/issues/38 for some alternatives.
