### ISSUE TITLE
We probably should not load essglobal into each Named Graph

### ISSUE THREAD

**Issue by matt-wallis** [p6data-coop/ise-linked-open-data#105]
Currently, we load essglobal into each named graph. The place where this is implemented is in the [triplestore.mk makefile](https://github.com/SolidarityEconomyAssociation/open-data-and-maps/blob/master/data/tools/se_open_data/makefiles/triplestore.mk). In particular, the lines:
```
@$(call GET_RDFXML_FOR_VIRTUOSO,$(ESSGLOBAL_URI)vocab/,essglobal_vocab.rdf)
@$(call GET_RDFXML_FOR_VIRTUOSO,$(ESSGLOBAL_URI)standard/legal-form,legal-form.skos)
@echo "Creating $(VIRTUOSO_NAMED_GRAPH_FILE)..."
@echo "$(GRAPH_NAME)" > $(VIRTUOSO_NAMED_GRAPH_FILE)
@echo "Creating $(VIRTUOSO_SCRIPT_LOCAL)..."
@echo "ld_dir('$(VIRTUOSO_DATA_DIR)','*.rdf',NULL);" > $(VIRTUOSO_SCRIPT_LOCAL)
@echo "ld_dir('$(VIRTUOSO_DATA_DIR)','*.skos',NULL);" >> $(VIRTUOSO_SCRIPT_LOCAL)
```
This seems like a bad idea! What is the reason for doing this? I suspect it goes back to early experimentations with OntoWiki, so that we could explore a dataset more fully, through the links to essglobal.

**Comment by ColmMassey** [comment]
We could try not doing it. Things will probably still work.
