### ISSUE TITLE
Make it possible to configure how readily map icons are merged into circles. 

### ISSUE THREAD

**Issue by ColmMassey** [p6data-coop/ise-linked-open-data#106]
(moving from email thread)
"What control do we have over when the numbered circles split/merge, and when all the bottom level icons are displayed?"

What are the parameters available to describe how the map decides when to cluster icons into a disk?
At the moment (24th Oct) all the maps seem too sparesly populated. Can we change that, so it merges icons and disks less frequently? It the extreme, is there an option to render all icons regardless of how dense. (Some icons could end up being completely invisible, or un clickable).

**Comment by matt-wallis** [comment]
We use the [Leaflet.markerCluster library](https://github.com/Leaflet/Leaflet.markercluster). Settings are documented there.

Before doing anything about this, we need to reach some kind of consensus that the current behaviour is not good enough - I'm yet to be persuaded of that :-)

**Comment by ColmMassey** [comment]
It does appear from a quick look at the library docs that there is a lot of flexibility in how this can be done.

I have two issues at the moment. 
The first is that the clustering is set too high now, so that the maps are always very sparsely populated. In the absense of different icon types, the only information we have before selecting an icon is distribution/density, which is not displayed well when over clustered.

The second point is only relevant once we have distinct icon types. Once we have this, again over clustering will mask all this information until we have zoomed right in close.

So right now, my only request would be to try relaxing the clustering.

**Comment by matt-wallis** [comment]
> I have two issues at the moment.
> The first is that the clustering is set too high now, so that the maps are always very sparsely populated. In the absense of different icon types, the only information we have before selecting an icon is distribution/density, which is not displayed well when over clustered.

I don't follow this. You can't select an icon while it is still clustered. I must be missing something.

> 
> The second point is only relevant once we have distinct icon types. Once we have this, again over clustering will mask all this information until we have zoomed right in close.

@ColmMassey Could you describe a use-case (or 2, if needed to illustrate the above points)?

**Comment by ColmMassey** [comment]
> I don't follow this. You can't select an icon while it is still clustered. I must be missing something.

I think my powers of description are insufficient. I'll demonstrate next time we're on a map together. It is not urgent.
