### ISSUE TITLE
Sort out character encoding issues from CSV

### ISSUE THREAD

**Issue by matt-wallis** [p6data-coop/ise-linked-open-data#107]
There are examples in the newcastle-mapjam data, imported via CSV from a google spreadsheet, as raised by @Clara-dos-Santos in https://github.com/SolidarityEconomyAssociation/open-data-and-maps-outreach/issues/123#issuecomment-435022947

Need to establish what character encoding is being used in the g spreadsheet - (sigh, one of the 'joys' of CSV files is that they don't declare their character encoding 👎 )

**Comment by matt-wallis** [comment]
Note the use of iconv in [to-utf8.rb](https://github.com/SolidarityEconomyAssociation/oxford-map/blob/master/data/to-utf8.rb).
A precursor to this is to find out (by trial and error loading a CSV into LibreOffice) what is the encoding of the CSV.
Here's a [list of encodings supported by ICONV](https://gist.github.com/hakre/4188459). The list is 6 years old, and may have grown since then.

**Comment by ColmMassey** [comment]
I think this covers the utf issue also present in the DotCoop data.

**Comment by ColmMassey** [comment]
See also https://github.com/SolidarityEconomyAssociation/open-data-and-maps-outreach/issues/171

**Comment by ColmMassey** [comment]
This seems to have been addressed, certainly in Oxford data.
