### ISSUE TITLE
Map very slow to load, and has other anomalies

### ISSUE THREAD

**Issue by matt-wallis** [p6data-coop/ise-linked-open-data#110]
This applies to the build of the map https://internal.solidarityeconomy.coop/maps/newcastle-mapjam/ which was deployed this morning.

@ColmMassey has experienced these problems using Firefox on Windows. Which version of Firefox are you using?

Others at NewBridge have also experienced problems.

I cannot reproduce these problems - it may well be confined to those with slow internet connections.

**Comment by matt-wallis** [comment]
Might this be caused by a Require.js timeout in loading modules? See https://requirejs.org/docs/api.html#config-waitSeconds on setting the timeout.

**Comment by matt-wallis** [comment]
I have hooked my laptop up to a 3G iPhone in order to attempt to test on a slow connection. But the map works fine. So I can't reproduce the problem. :-(

**Comment by ColmMassey** [comment]
I guess we need to leave it until it reappears. Next time we hook up, lets test Jutsi screen sharing. If is is still faky, let's try Zoom screen sharing. Need to have reliable ways of testing remotely.

**Comment by matt-wallis** [comment]
Browser detection should be added to the code.
See https://stackoverflow.com/questions/29046635/javascript-es6-cross-browser-detection

**Comment by ColmMassey** [comment]
Did you have any ideas about what could be causing this, for a a starter for Joe to look at, if it reoccurs?

**Comment by ColmMassey** [comment]
Do you want to get the satisfaction of closing this one?
