### ISSUE TITLE
Open source online survey tools

### ISSUE THREAD

**Issue by VersteegenAudrey** [p6data-coop/ise-linked-open-data#111]
After a super quick search - this article sums it up the best. What do you think would be the best of the 4? 
LimeSurvey comes up the most often, but reading this I am wondering whether JDEsurvey is better? But it may come down to tech stuff I am not familiar enough with.

**Comment by matt-wallis** [comment]
> this article

which article? :-)

**Comment by VersteegenAudrey** [comment]
Darn. 
This one: https://opensource.com/article/17/2/tools-online-surveys-polls

**Comment by matt-wallis** [comment]
I asked a question on the CoTech forum:
https://community.coops.tech/t/foss-survey-questionnaire-tools-available-in-cloud/1115

**Comment by matt-wallis** [comment]
Hi @VersteegenAudrey - is there anything more to do for this issue? If not, please close it. Thank you.
