### ISSUE TITLE
Improve history navigation and panel close buttons

### ISSUE THREAD

**Issue by ColmMassey** [p6data-coop/ise-linked-open-data#115]
"I wouldn't have noticed that I could go forwards and backwards in the history if you hadn't suggested it. After seeing it suggested, it was easy to work out how."

What can be done to make this more obvious for the first time user.

"On a mobile, the close sidebar button is very small. It requires care not to press the settings button beside it. So either, can we make it slightly larger, or move the other button away, to the other side, of the bar, perhaps?"

I think these could be addressed together.

**Comment by ColmMassey** [comment]
See https://github.com/SolidarityEconomyAssociation/open-data-and-maps/issues/100#issuecomment-437060558 and https://github.com/SolidarityEconomyAssociation/open-data-and-maps-outreach/issues/123#issuecomment-442018433

**Comment by ColmMassey** [comment]
@joebillings Is this addressed in the panel design changes you have proposed?

**Comment by joebillings** [comment]
Yes, the close button hangs on the sticks to the right side of the panel when it's opened. The navigation buttons are out of the way on the left hand side.

<img width="344" alt="Screenshot 2019-05-01 at 12 18 22" src="https://user-images.githubusercontent.com/411367/57015206-69fae080-6c0b-11e9-9042-93825bcc774e.png">
