### ISSUE TITLE
Restrict area to which map can be zoomed out

### ISSUE THREAD

**Issue by matt-wallis** [p6data-coop/ise-linked-open-data#117]
For some local maps, we want to prevent the map from being zoomed out beyond specified limits.

This was identified as a specific requirement for the Oxford map at a meting today with @Clara-dos-Santos @SEAKatDarling and @ColmMassey.

This is closely related to #116.

**Comment by joebillings** [comment]
See this: https://stackoverflow.com/questions/22155017/can-i-prevent-panning-leaflet-map-out-of-the-worlds-edge
