### ISSUE TITLE
Update LOD we are publishing from Co-ops UK Data to latest

### ISSUE THREAD

**Issue by ColmMassey** [p6data-coop/ise-linked-open-data#119]
Co-ops UK are now publishing data quite regulraly. (Qly perhaps even)

Assess what has changed to the structure of the data and republish the latest set.

---
#### TaskJuggler
TJ: effort 6h
TJ: depends-on #66

**Comment by ColmMassey** [comment]
>it depends if anything has changed in the CUK data, and if there's anything lurking in our data processing software that needs fixing - it's been a long time since we last processed CUK data. I've got some vague memory that there's an issue to do with creating the sameAs relationships between CUK and dotcoop data.
>

**Comment by ColmMassey** [comment]
The latest data from Co-ops UK is [here](https://nextcloud.solidarityeconomy.coop/index.php/f/31635) or ..NextCloud/CodeOperatives/open_data_organisations_2019_q3.csv. Let's focus on only co-ops, not outlets for this issue. Create a new graph for it and a map-app that points just to that data.

**Comment by ColmMassey** [comment]
Let's use ..NextCloud/CodeOperatives/FieldMapping.ods document to specify how to interpret the fields in the Co-ops UK data as fields in the standard.csv format. The ones with green highlighting are straight forward. Code them first.

**Comment by ColmMassey** [comment]
In the 2019q3 outlets data, ### open_data_outlets_2019_q3.csv  for many co-op outlets there are duplicates. For example 

R000001 | Co-operative Group Limited | The Co-operative Food - Tiree |
appears 4 times. 

Need to find out why that is, but for the moment, can we only upload one outlet per Co-op/postcode?

**Comment by ColmMassey** [comment]
I have email data@uk.coop to see if they can shed any light.

**Comment by sunnydean** [comment]
When we see multiple entries for an outlet we just see the same entry but with a different phone number

**Comment by sunnydean** [comment]
We have currently uploaded the latest data at https://w3id.solidarityeconomy.coop/coops-uk/test2019/ . We had issues due to multiple entries for the same outlet but with a different phone number. I have written a script to remove the duplicates, but we need to use the phone numbers. We have to combine the phone numbers into one field (as we do for websites in dotcoop) and we will have successfully updated the data.
