### ISSUE TITLE
Experimental nav bar not working on mobile

### ISSUE THREAD

**Issue by matt-wallis** [p6data-coop/ise-linked-open-data#126]
With reference to the experiment:

> https://internal.solidarityeconomy.coop/experiments/flexbox-navbar-app-plus-site/

> (login required for access to internal - see SolidarityEconomyAssociation/open-data-and-maps-outreach#123 for details)

@SEAKatDarling reports problems going back to Map tab: https://github.com/SolidarityEconomyAssociation/open-data-and-maps/issues/118#issuecomment-445195983

**Comment by matt-wallis** [comment]
Hi @SEAKatDarling - could you please visit on your phone: https://internal.solidarityeconomy.coop/experiments/17-alpha-test/example-embedding-site-index.html

If you can no longer reproduce the problem you reported at https://github.com/SolidarityEconomyAssociation/open-data-and-maps/issues/118#issuecomment-445195983, then I think this issue can be closed.

**Comment by SEAKatDarling** [comment]
Yep it works fine now!
