### ISSUE TITLE
Map-app component should not disable console logging

### ISSUE THREAD

**Issue by matt-wallis** [p6data-coop/ise-linked-open-data#127]
When the map-app is built, debugging is turned off, and [console.js](https://github.com/SolidarityEconomyAssociation/open-data-and-maps/blob/master/map-app/www/app/console.js) disables the console functions.

This is not a good thing when the map-app is embedded: the page into which it is embedded may well want to keep the console working normally!

But we still want to retain a way for the console logging within the map-app to be turned off when we build it for release.

-----
#### TaskJuggler
tj: effort 4h

**Comment by ColmMassey** [comment]
Is this still an issue?

**Comment by joebillings** [comment]
I'm closing this. The console seems to work fine for me in Chrome, Safari and Firefox.
