### ISSUE TITLE
Move from requirejs to webpack

### ISSUE THREAD

**Issue by matt-wallis** [p6data-coop/ise-linked-open-data#132]
This will provide more flexibility, and allow us to build the package in a way that works better on more platforms (e.g. by transpiling using Babel). 
The whole development set-up can be simplified, with all of our dependent libraries available via NPM.
Currently, using requirejs to load the application is awkward. 
See in [map-app.js](https://github.com/SolidarityEconomyAssociation/open-data-and-maps/blob/development/map-app/www/map-app/map-app.js), the dynamic construction of:
```
<script data-main="app" src="lib/require.js"></script> 
```
This (probably) gets in the way of adding the `<map-app>` custom element to the shadow DOM, and makes it difficult to pass cleanly child elements to the custom element - for example,  child elements that contain the datasets to be included in this instance of the map-app.

**Comment by matt-wallis** [comment]
Resources:
- [Moving from requirejs to webpack](https://gist.github.com/xjamundx/b1c800e9282e16a6a18e)
- [webpack](https://webpack.js.org/)
- [webpack - how to](https://github.com/petehunt/webpack-howto)
- [embedding version](https://github.com/webpack/webpack/issues/237)
- [loading data](https://webpack.js.org/guides/asset-management/#loading-data)

We need to move from AMD to ES2015 modules when we do this.

Here's an example `package.json` for the map-app (taken from bombyx:~/SEA/open-data-and-maps/experiments/webpack/01-basics):
```
{
  "name": "01-basics",
  "version": "1.0.0",
  "description": "",
  "private": true,
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "webpack": "^4.28.1",
    "webpack-cli": "^3.2.1"
  },
  "dependencies": {
    "d3": "^5.7.0",
    "leaflet": "^1.4.0",
    "leaflet-contextmenu": "^1.4.0",
    "leaflet.awesome-markers": "^2.0.5",
    "leaflet.markercluster": "^1.4.1",
    "postal": "^2.0.5",
    "require": "^2.4.20"
  }
}
```
(should be able to remove `require` from that once the AMD modules have been changed to ES2015).

**Comment by joebillings** [comment]
✋I'd be happy to look into this

**Comment by ColmMassey** [comment]
Is this still relevant. Please close @wu-lee,  if not.

**Comment by wu-lee** [comment]
Yes, I think this is still a good idea, what do you think @dtmakm27?

Webpack is the go-to build tool for React IIRC, but isn't specifically for React, and also has some sort of support for RequireJS/AMD modules, which might be helpful (if we don't decide to convert the modules to the ES2015 style).

**Comment by sunnydean** [comment]
I do agree with you @wu-lee. I suggest we discuss with the rest of the code-operative first to make sure we can have some cross comparability. 
Other than that, yeah it seems like a sensible choice

**Comment by ColmMassey** [comment]
If there were other synergies with this direction, then all the better. Just a matter of choosing when to do that work.
