### ISSUE TITLE
Improve map performance when changing selections

### ISSUE THREAD

**Issue by matt-wallis** [p6data-coop/ise-linked-open-data#133]
To see the problem:
- Run the all-datasets map-app
- perform a search
- now show all initiatives
- now use history keys

**Comment by ColmMassey** [comment]
@matt-wallis can you share any thoughts you had about candidates to improve here, that would be great.

**Comment by joebillings** [comment]
Possibly slow dom-updates

**Comment by ColmMassey** [comment]
I think this can be closed?
