### ISSUE TITLE
Design how search interacts with activity filter

### ISSUE THREAD

**Issue by ColmMassey** [p6data-coop/ise-linked-open-data#136]
As we extend the map-app to allow filtering on Activity type, we need clarity on how that works with the text search functionality. We wish to be able to filter on mutliple activities simultaneously and also narrow that selection with a text matching search. We need to modify the existing mockups to show how this would work, (on both mobile and wide screen).

**Comment by ColmMassey** [comment]
Essential that the panels, search box and visualised icons stay state locked.

**Comment by ColmMassey** [comment]
Can you put a link to the latest Sketchup you created for this in this Issue @joebillings ? Ta.

**Comment by joebillings** [comment]
Mobile: https://sketch.cloud/s/75lep/wLPePJl/play
Desktop: https://sketch.cloud/s/75lep/jgx5xA7/play

**Comment by joebillings** [comment]
Some things to think about:

- Should the search results/items displayed on the map live update when activities are selected/deselected?
  - It might be a nice way to quickly filter all the items to a single activity:
    1. Open up the filters (desktop: click the arrow next to search, mobile: click the search icon then the arrow next to search)
    2. Check "Environment"
    3. Only the Environment initiatives are displayed
  - It could also make search more friendly:
    1. Search for "Oxford"
    2. All initiatives with the text "Oxford" are listed
    3. Open up the filters (desktop: click the arrow next to search, mobile: click the search icon then the arrow next to search)
    4. Check "Environment"
    5. Only the Environment initiatives with the text "Oxford" are displayed
  - One potential downside is that live updating could over-saturate the state stack (back/forward buttons)

**Comment by ColmMassey** [comment]
The example in the link is out of sync with the description above. As with the maps, we probably need a simple version control system here. Let's discuss what that might look like, in conjunction with the map version ticket [here](https://github.com/SolidarityEconomyAssociation/open-data-and-maps/issues/134).

**Comment by sunnydean** [comment]
Currently you can filter the initiatives based on one filter (e.g. Australia)
This will hide all other markers from the map except the ones in Australia

Usability for when search has also been added (e.g. clicking on show directory hides, search, can search filters by just clicking on show directories and typing and etc.)

The search operates either on all of the initiatives if you have not selected filters
Or operates on the filters selected (e.g. if you clicked on australia in the directories tab)

Support for multiple filters is here and it is just a matter of visualising them

**Comment by sunnydean** [comment]
A simple solution for visualising multiple filters is a checkbox next to each country
i.e. having something like this in the directories tab:
Australia [check]
Argentina [check]
United Kingdon []


i will try to produce a small demo in the next day or two

**Comment by sunnydean** [comment]
Although not done, is this enough for the current iteration? (without the checkbox and multiple filters) @ColmMassey 

(a new issue should be made for multiple filters)

**Comment by ColmMassey** [comment]
Let's leave multi filters for later. Happy to close this.
