### ISSUE TITLE
Implement new activity filter functionality 

### ISSUE THREAD

**Issue by ColmMassey** [p6data-coop/ise-linked-open-data#137]
Essentially implementing what is designed [here...](https://github.com/SolidarityEconomyAssociation/open-data-and-maps/issues/136)

Tech Dependencies
---------------------
- [ ] https://github.com/SolidarityEconomyAssociation/open-data-and-maps-outreach/issues/163

**Comment by joebillings** [comment]
Linking: https://github.com/SolidarityEconomyAssociation/oxford-map/issues/25
