### ISSUE TITLE
Implement new design for map pop-up

### ISSUE THREAD

**Issue by ColmMassey** [p6data-coop/ise-linked-open-data#138]
![image](https://user-images.githubusercontent.com/1162642/57015820-bbf13580-6c0e-11e9-9bb1-772601777e46.png)

**Comment by ColmMassey** [comment]
Might be some relevant info [here](https://github.com/SolidarityEconomyAssociation/open-data-and-maps/issues/77)

**Comment by joebillings** [comment]
This is complete, bar a few minor tweaks: http://163.172.189.71:8787/

**Comment by ColmMassey** [comment]
Still not implemented yet on mobile

**Comment by ColmMassey** [comment]
There isn't a map pop up in the mobile version, but as there isn't a dedicated Issue for implementing displaying the same data in the side bar, we could keep Issue this open until that is in place.
