### ISSUE TITLE
Extend Search to include domain names and address

### ISSUE THREAD

**Issue by ColmMassey** [p6data-coop/ise-linked-open-data#139]
Current search just operates on the organisation's name. 'Or'ing with a search across address fields and domain fields would be very useful.

Larger discussion on search possiblities [here](https://github.com/SolidarityEconomyAssociation/open-data-and-maps/issues/84)

**Comment by ColmMassey** [comment]
Might be something useful [here](https://github.com/SolidarityEconomyAssociation/open-data-and-maps/issues/60)

**Comment by sunnydean** [comment]
Added, you can lookup domains or locations from the main search bar. @ColmMassey 
Essentially you are looking for the searched words in the initiatives:
name, dataset, www, locality, postcode, and country 
http://dev.playground.solidarityeconomy.coop/

**Comment by ColmMassey** [comment]
Is Street Address indexed in the search?

**Comment by sunnydean** [comment]
Not currently, shall I add that in?

I avoided street address for clearer results when looking up geo positions 
E.g. searching Austria will result in
All coops in Austria 
And 
A coop with a street address of 23 Austria Road

**Comment by ColmMassey** [comment]
That's fine. Was just checking as I noticed it.
