### ISSUE TITLE
Use Docker to containerise server and required tools

### ISSUE THREAD

**Issue by joebillings** [p6data-coop/ise-linked-open-data#140]
[Docker](https://www.docker.com/) is a container platform for installing tools and apps in their own ring-fenced environments. By using it we can easily upgrade tools we're using ([Virtuoso for instance](https://github.com/SolidarityEconomyAssociation/open-data-and-maps/issues/104)) on the same server without disrupting existing installations.

We can also package up containers and make them available to partners so they can easily install everything required to run a map on their server.

**Comment by wu-lee** [comment]
See also https://github.com/SolidarityEconomyAssociation/open-data/issues/38
