### ISSUE TITLE
Html formatting of initiative data error

### ISSUE THREAD

**Issue by ColmMassey** [p6data-coop/ise-linked-open-data#142]
The html generated when looking at data on initiatives in Newcastle

https://data2.solidarityeconomy.coop/sea-lod/newcastle-mapjam/ThePicklePalace.html

is formatted differently to Oxford pilot

https://data2.solidarityeconomy.coop/sea-lod/oxford-pilot/88.html

**Comment by joebillings** [comment]
I know what's happening here (there's a missing stylesheet). I'll republish all the latest NewBridge data in the next day or two and fix this then.
