### ISSUE TITLE
Add a link to the LOD for demo purposes

### ISSUE THREAD

**Issue by joebillings** [p6data-coop/ise-linked-open-data#145]
We discussed the removal of Geek Zone as per this ticket: https://github.com/SolidarityEconomyAssociation/oxford-map/issues/19

A decision was made to replace it with a link to each initiative's LOD but only on maps intended for tech demo purposes.

**Comment by ColmMassey** [comment]
I think we should reintroduce the link to the data from the Oxford about box, using the same description as the Newbridge map. Then close the Issue.
