### ISSUE TITLE
Revisit RDF generation for Twitter and Facebook 

### ISSUE THREAD

**Issue by joebillings** [p6data-coop/ise-linked-open-data#149]
Generating the appropriate RDF for Facebook and Twitter was taking too long so I've parked it for now. Here's the format they need to take:

**RDFXML**

<foaf:account>
  <foaf:OnlineAccount>
    <rdf:type rdf:resource="http://xmlns.com/foaf/0.1/OnlineAccount"/>
    <foaf:accountServiceHomepage 
            rdf:resource="http://twitter.com/"/>
    <foaf:accountName>solidarityeconomyassociation</foaf:accountName>
  </foaf:OnlineAccount>
</foaf:account>
<foaf:account>
  <foaf:OnlineAccount>
    <rdf:type rdf:resource="http://xmlns.com/foaf/0.1/OnlineAccount"/>
    <foaf:accountServiceHomepage 
            rdf:resource="http://facebook.com/"/>
    <foaf:accountName>solidarityeconomyassociation</foaf:accountName>
  </foaf:OnlineAccount>
</foaf:account>

**TTL**

foaf:account [
  a foaf:OnlineAccount ;
  foaf:accountServiceHomepage <http://www.twitter.com/> ;
  foaf:accountName "solidarityeconomyassociation"
], [
  a foaf:OnlineAccount ;
  foaf:accountServiceHomepage <http://www.faebook.com/> ;
  foaf:accountName "solidarityeconomyassociation"
] ;

**Comment by joebillings** [comment]
Linkeddata library docs: https://rubydoc.info/github/ruby-rdf/rdf

**Comment by sunnydean** [comment]
Hey @ColmMassey 
what was the problem with this?

**Comment by sunnydean** [comment]
@ColmMassey 
I deployed a twitter/facebook containing graph here: https://data1.solidarityeconomy.coop/sea-lod/oxford-pilot/

e.g.
https://data1.solidarityeconomy.coop/sea-lod/oxford-pilot/149.html#twitter

**Comment by sunnydean** [comment]
@ColmMassey 
this is done at: 
https://dev.oxford.solidarityeconomy.coop/

**Comment by ColmMassey** [comment]
> Hey @ColmMassey
> what was the problem with this?

I can't remember. I'll ping Jo and send what you have done.

**Comment by joebillings** [comment]
Hey all - it was just taking me too long to figure out how to get the Ruby RDF library to do what I wanted to do so had to move on to other things @ColmMassey

**Comment by sunnydean** [comment]
Ah, cool. I've fixed it i think.
You were using a string literal to FOAF instead of the VOCAB object when passing one of the parameters (which broke the generation code a bit).
Fixed now @ColmMassey

**Comment by ColmMassey** [comment]
Thanks Joe
