### ISSUE TITLE
World scale map-app tweaks

### ISSUE THREAD

**Issue by ColmMassey** [p6data-coop/ise-linked-open-data#154]
Several tweaks we should try to optimise when the map app is looking at a world rather then regional data set. 

- [x] Transition needed when moving between locations: What options are there? 
- [x] Identify good default zoom distance when moving to a new location  - make this configurable. 
- [x] Set opening zoom level to encompass the world
- [ ] Provide option to use mobile behaviour even when behaviour in large screen. (This might work better on world scale, as there may be no org description. )

**Comment by joebillings** [comment]
The new zooming functionality and selection makes the map more usable on desktop when looking at a world-scale map. Shall we remove the last one or would you like me to add an option into the config?

**Comment by ColmMassey** [comment]
OK. Let's leave it.
