### ISSUE TITLE
Add Vanilla Co-operative to Organisational Types

### ISSUE THREAD

**Issue by ColmMassey** [p6data-coop/ise-linked-open-data#155]
Some data sets will indicate that an organisation is a co-op, but not what type of co-op. Do we use the ESSGlobal legal-form which has a vanilla _Cooperative_ label, or add a generic _Co_operative_it to our newly minted _Organisation Strusture_.

**Comment by joebillings** [comment]
I think we'll need to add a generic one as I don't think we can switch between SKOSs like that

**Comment by ColmMassey** [comment]
Lets do that.

**Comment by joebillings** [comment]
Here is the vanilla coop: http://vocabs.solidarityeconomy.coop/essglobal/V2a/html-content/essglobal.html#organisational-structure-OS115
