### ISSUE TITLE
Add Long and Lat options to Surveys

### ISSUE THREAD

**Issue by ColmMassey** [p6data-coop/ise-linked-open-data#156]
Create the option for those using the survey to add long and lat. It's pretty easy to generate a long and lat from OSM or google maps. 
What would it take to be able to grap long and lat from, say clicking on our map interface. Could then be easily copied into the survey? 

We then just need the importer to add that too.

**Comment by joebillings** [comment]
Is the postcode lookup tool not working?

**Comment by ColmMassey** [comment]
We know the postcode lookup tool is only ever approximate. The larger the postcode area the more inaccurate it will be. One user reported that their organisation was in the wrong place, as they didn't know that the positioning postcode based. Enabling this functionality (at some point) would allow users to more accurately position themselves.

**Comment by ColmMassey** [comment]
This is a limsurvey issue, not a pipleline issue. Needs to be done survey by survey, when not expecting anyone to be updating.

**Comment by ColmMassey** [comment]
Have now added ability to locate your initiative on an openstreet map window when entering the survey. It is a little crude I could prepopulate the search with the address just entered and the search is rubbish, but it is just something done once, so not urgent to improve it. When exported the result is in one entry called _location_ with lat and long separated by a semi colon. @wu-lee @dtmakm27
