### ISSUE TITLE
Organisational Structure isn't loading in latest map

### ISSUE THREAD

**Issue by joebillings** [p6data-coop/ise-linked-open-data#166]

**Comment by joebillings** [comment]
(See https://github.com/SolidarityEconomyAssociation/open-data-and-maps/issues/150#issuecomment-535449806 for my proposed solution to this)

**Comment by sunnydean** [comment]
Done, for dot coop all of them are cooperatives (as expected), but it is not hard-coded, the registered organisation is pulled from the linked data

http://dev.playground.solidarityeconomy.coop/

@ColmMassey

**Comment by ColmMassey** [comment]
Great. Let's leave it open til we check how it looks in a version with multiple org types, but I'll move it to completed wrt this sprint.

**Comment by sunnydean** [comment]
pull in the organisation structure name instead of the organisation structure code

**Comment by ColmMassey** [comment]
What initiatives have multiple organisation types? ICA will whne we finish the ESSGlobal extensions. Any others?

**Comment by ColmMassey** [comment]
Actually SEA in the oxford map has two! Can we update dev.oxford, so we can test this?

**Comment by sunnydean** [comment]
We should be actually querying them in the same SPARQL query, rather than working around and processing the data in the JS scripts.
But this will definitely require us to update Virtuoso (https://stackoverflow.com/questions/42010103/group-concat-in-sparql#comment71199775_42010103)

**Comment by ColmMassey** [comment]
Can we easily hack this and https://github.com/SolidarityEconomyAssociation/open-data-and-maps/issues/150#issuecomment-654233306

for the moment until we deal with the virtuoso upgrade? Is there a ticket for the virtuoso ugrade somewhere?

**Comment by sunnydean** [comment]
> Can we easily hack this and #150 (comment)

Sure :)

There is not an issue about updating Virtuoso currently (checked both June and July)

**Comment by sunnydean** [comment]
BTW should secondary activities be indexed in the Directory?  (i.e. should get initiatives with education listed as a secondary activity when you click on Education in the directory?)

**Comment by sunnydean** [comment]
@ColmMassey 
added the current hack here : https://dev.oxford.solidarityeconomy.coop/
We should update virtuoso though, it will allow us to query data in a bit more versatile way
