### ISSUE TITLE
Map clusters not opening up when 2 initiatives have same address.

### ISSUE THREAD

**Issue by ColmMassey** [p6data-coop/ise-linked-open-data#167]
I noticed on the Newbridge map that one can often end up in a situation where you have two items at the same place (e.g. Dwellbeing) and you have a cluster of 2 that you cannot open out into a spider.

**Comment by joebillings** [comment]
I can't repeat this.

**Comment by ColmMassey** [comment]
I am still seeing it, on Firefox and Chrome. I used anonymous view, to be sure I had the latest code.

**Comment by ColmMassey** [comment]
Seems fixed in latest instance of Newbridge map.
