### ISSUE TITLE
Creating Linked Data Readme Corrections/Changes

### ISSUE THREAD

**Issue by ColmMassey** [p6data-coop/ise-linked-open-data#169]
https://github.com/SolidarityEconomyAssociation/open-data-and-maps/blob/development/data/docs/README.md

**Comment by ColmMassey** [comment]
In the prerequisite perhaps say
 a little about the virtuoso server
which permissions/passwords you will need to complete the process.

Typos
macOS is Unix based so its cliENT?
. We might, for instance, wanT?
For instance, if the filedS? that we want to use as the Identifier

**Comment by ColmMassey** [comment]
Add note:
If using an Ubuntu virtual machine on Window 10, you should be able to access the c drive of your windows operating system via /mnt/c.

**Comment by ColmMassey** [comment]
Should we comment on the interim files initiatives.csv and reports.csv?

**Comment by joebillings** [comment]
> In the prerequisite perhaps say
> a little about the virtuoso server
> which permissions/passwords you will need to complete the process.

We need to be careful about what we put up onto the public repo.

> Typos
> macOS is Unix based so its cliENT?
> . We might, for instance, wanT?
> For instance, if the filedS? that we want to use as the Identifier

Fixed

**Comment by joebillings** [comment]
> Should we comment on the interim files initiatives.csv and reports.csv?

Yes - I'll add a note to explain what they are and that they'll need deleting if an error has occurred and we want to run the makefile again.

**Comment by ColmMassey** [comment]
>Yes - I'll add a note to explain what they are and that they'll need deleting if an error has occurred and we want to run the makefile again.
Similarly with the sql interim triplestore file, referencing the intermediary files expected to be produced makes debugging easier. What others might help?

**Comment by ColmMassey** [comment]
Should we mention the two error messages, or would it be quicker for you to just go in and see if you can change the debug message to warnings?

**Comment by joebillings** [comment]
> Should we mention the two error messages, or would it be quicker for you to just go in and see if you can change the debug message to warnings?

I think we should change the message to make it seem less ... drastic

**Comment by ColmMassey** [comment]
@ThomasDavisonsGit Can you close this if you think it is obsolete?

**Comment by ThomasDavisonsGit** [comment]
> @ThomasDavisonsGit Can you close this if you think it is obsolete?

Hi @ColmMassey. Did you mean to tag someone else? I haven't been working on this issue.

**Comment by ColmMassey** [comment]
I am purging old tickets. This one was about earlier attempts to clean up linked data documentation. So I jsut ran it by you to see if there was anything of value there from your perspective. The primary link is not even valid anymore, so don't worry about it.
