### ISSUE TITLE
Push Development Branch to Master

### ISSUE THREAD

**Issue by ColmMassey** [p6data-coop/ise-linked-open-data#170]
As the current Development branch is going to be the production code for a while now, we should push it to the Master. Use the opportunity to clean away all the experiments that currently clutter it.

**Comment by ColmMassey** [comment]
Can you close this one too when this is done.

**Comment by wu-lee** [comment]
This is now done.

**Comment by ColmMassey** [comment]
For sea-map and open-dat_and_maps?

**Comment by wu-lee** [comment]
For `open-data-and-maps`. 

The `sea-map` repo never had a `development` branch, just `master`. Perhaps it should do but that depends on our workflow style. 

It makes sense when you do testing on a branch, and then merge across to master when it's passed all the tests. Master then only contains point releases.

But sometimes your system is composed of lots of components which aren't really deployed or integration-tested individually - in which case I think there'd be a repository in which the integration is configured (i.e. a top level repo which pulls in all the components), and the integration/testing is done on a branch there.

I think `sea-map` is arguably a component in this latter case.  And then *map applications* which use it are where the integration happens - these therefore might have development branches, and the specific release tag in `sea-map` is referenced by the `package.json` file there. So  `sea-map` would have feature branches and the like, and release tags consuming projects can reference, but perhaps not a development branch. (Although I don't think it hurts, it might not add much more than extra effort if you're not doing the testing there.)

**Comment by wu-lee** [comment]
As an aside, for a discussion and an example of a branch workflow with dev and feature branches see 'git flow': <https://nvie.com/posts/a-successful-git-branching-model/>
