### ISSUE TITLE
Check UK co-ops in DotCoop data and Co-opsUK data for duplicates

### ISSUE THREAD

**Issue by ColmMassey** [p6data-coop/ise-linked-open-data#177]
Requirements: Functioning graphs for Co-ops UK and Dot Coop co-ops.

Loop through all UK DotCoop co-ops.
  Look for Co-ops UK co-op with same postcode.
  and very similar names
    compare after removing whitespace, lower all caps and remove "limited", "ltd" etc.
  If you get a match create a sameas triple connecting the two co-ops.
  Add this triple to the both graphs.

**Comment by sunnydean** [comment]
Need to create query which:
identify targets of same as and merge both participating rows
url is dot-coop url 
description is coop-uk desc

**Comment by sunnydean** [comment]
We are using the old structure for generating sameas predicates, it works on the current data
