### ISSUE TITLE
Display UK DotCoop data and Co-opsUK data merging results when co-ops occur in both datasets

### ISSUE THREAD

**Issue by ColmMassey** [p6data-coop/ise-linked-open-data#178]
Something like this
https://sketch.cloud/s/75lep/a/94nKMM/play

**Comment by ColmMassey** [comment]
As of the morning of 12/12 we can load dotcoop (12/04/2019), or co-opsuk(q3/2019) or both. Looking closely at the Edinburgh Bicycle co-op (in Edinburgh) I'm seeing the following..
 - In the Co-ops UK graph, there is one entry for the co-op and one for the outlet. They have the same postcode, but the rest of the address has differences. The outlet also has a description. Neither has a website. Both have sameas links to the dot-coop uri.

 - In the DotCoop graph, there is only one for the co-op. It has the same postcode as the Co-ops UK data, but the rest of the address has difference to both the Co-ops UK entries. It has a website. It has geo data and a URI for ordanance survey. It has sameas links to both coopsuk entries.

- On the map when loading for the first time (mixed sources) I see 2 icons at same location for Edinburgh Bicycle co-op (in Edinburgh). They are identical except for the fact that one has a description. They both use the street address from dotcoop.

This looks exactly as I would expect. :-)

**Comment by ColmMassey** [comment]
If I switch to just using the DotCo-op data it still presents to icons for Edinburgh Bicycle co-op in Edinburgh. The data is identical. Any ideas why this might be the case?

**Comment by ColmMassey** [comment]
Toggling back to the co-ops-uk data set, I can't find the Edinburgh Bicycle co-op at all?

**Comment by sunnydean** [comment]
To merge the data we first take the duplicated ones between each table and merge them. Then we take the entries that do not contain a sameas predicate from one table. Then we take the entries that do not contain a sameas predicate from the other table.

We are hard-coding the merge currently and have not made it generic (i.e. you can merge only coops uk and dotcoop datasets). We also have hard-coded the way the merging works, we are currently taking the following fields from the tables:

coopsuk
- name
- description
- URI (unique identifier for the entry)
- registered organisation number

dotcoop
- homepage
- address
- lat
- long

merged results
- name
- description
- URI (unique identifier for the entry)
- registered organisation number
- homepage
- address
- lat
- long
