### ISSUE TITLE
Tease apart what should be where between About and new Databases tab

### ISSUE THREAD

**Issue by ColmMassey** [p6data-coop/ise-linked-open-data#179]
We now have a 'selected database' view in the panel, to support selection when more then one linked data graph is being used to populate the directory/map.

We have the following type of info to be displayed somewhere.

1. HTML/Text describing the project the map is serving. It could include URL's, like to the newbridge project, or to an SEA page.
2. A statement about the map-app software with a URL pointing to an appropriate github landing page.
3. Hyperlinks to the URIs of all the graphs whose data is available to be viewed.

Let's keep 1 and 2 in the i/About panel, and have 3 in the database page.

Let's have an option on the configuration file to disable the database panel altogether. The reason for this is that in the past, we often had requests to keep the interface as clean and untechnical as possible, for some audiences.

**Comment by wu-lee** [comment]
1. and 2. seem to be both defined in the `about.html` page already, correct?

 And 3. are listed in the database page already, correct?

Tentatively implemented a configurable option `showDatasetsPanel` on the branch `dot-coop-coops-uk-merge`.

**Comment by sunnydean** [comment]
We have a pretty good idea of what is needed. Will be discussed with Nick and Colm today to make sure we understand the task.

**Comment by sunnydean** [comment]
to solve 1 and 2 we just need a write up for the about section for the dotcoop/coops-uk2019 merger

**Comment by wu-lee** [comment]
That's an action for Colm (supply the text for the about page etc.). 

Given that, I think I understand what to do, but will make a sketch just to confirm.

**Comment by wu-lee** [comment]
If I'm right this should clarify?

Point 1 and 2:
![Screen Shot 2019-12-19 at 10 46 35](https://user-images.githubusercontent.com/67825/71169418-c5d4b100-2250-11ea-855f-1771373816b7.png)

Point 3
![Screen Shot 2019-12-19 at 10 46 25](https://user-images.githubusercontent.com/67825/71169443-d2f1a000-2250-11ea-9f10-c1df27235239.png)

The final point is just to make the datasets tab optional, by a parameter in `config.json`

**Comment by ColmMassey** [comment]
Can you point to the place in the repository where the About html is put for the current Oxford and DotCoop maps?

**Comment by ColmMassey** [comment]
What else should we put in the About? A version #?

**Comment by wu-lee** [comment]
> Can you point to the place in the repository where the About html is put for the current Oxford and DotCoop maps?

This, for example, defines what goes into the about tab for the coops UK 2017 "variant" of the map-app. Each variant can have its own.

https://github.com/SolidarityEconomyAssociation/open-data-and-maps/blob/master/map-app/variants/coops-uk2017/about.html

The about is fairly free-form.  But we could pull in the version from the version.json file which is generated when the map-app site is built.

**Comment by wu-lee** [comment]
@ColmMassey - is this ticket still a priority for Code Operative Org Sprint 2? Or should we down-prioritise it?

**Comment by ColmMassey** [comment]
Yes, let's leave this until next month.

**Comment by ColmMassey** [comment]
I'm splitting this issue into 

1. Design of [Show info](https://github.com/SolidarityEconomyAssociation/sea-map/issues/17) panel; 
2. Design of [Datasets](https://github.com/SolidarityEconomyAssociation/sea-map/issues/18) panel;
3. New config options required; https://github.com/SolidarityEconomyAssociation/sea-map/issues/19

We can postpone working on 2 until we are finalising a multi graph map implementation.
