### ISSUE TITLE
Sort directory listing alphabetically

### ISSUE THREAD

**Issue by ColmMassey** [p6data-coop/ise-linked-open-data#182]
Entries in the directory should be displayed in alphabetical order.
The current oxford and newbridge maps, which use Primary Activites it appears alphabetically.
In both the latest 12/12/19 dotcoop-co-opsuk build and the dotcoop build where locality and country are used, it isn't sorted.

**Comment by sunnydean** [comment]
Done, listings are sorted  @ColmMassey 
http://dev.playground.solidarityeconomy.coop/

**Comment by ColmMassey** [comment]
![screenshot-dev playground solidarityeconomy coop-2020 02 27-16_02_42](https://user-images.githubusercontent.com/1162642/75461983-6c3ce100-597b-11ea-87bb-245bc5a94885.png)
![screenshot-dev playground solidarityeconomy coop-2020 02 27-16_09_10](https://user-images.githubusercontent.com/1162642/75462080-9393ae00-597b-11ea-8374-161bc3dd58f3.png)

**Comment by ColmMassey** [comment]
Still unsorted in the version I have reviewed.

**Comment by sunnydean** [comment]
https://dev.playground.solidarityeconomy.coop/
Should be fixed now
