### ISSUE TITLE
Design work on how sameas merging works

### ISSUE THREAD

**Issue by sunnydean** [p6data-coop/ise-linked-open-data#184]
To merge the data we first take the duplicated ones between each table and merge them. Then we take the entries that do not contain a sameas predicate from one table. Then we take the entries that do not contain a sameas predicate from the other table.

We are hard-coding the merge currently and have not made it generic (i.e. you can merge only coops uk and dotcoop datasets). We also have hard-coded the way the merging works, we are currently taking the following fields from the tables:

coopsuk

    name
    description
    URI (unique identifier for the entry)
    registered organisation number

dotcoop

    homepage
    address
    lat
    long

merged results

    name
    description
    URI (unique identifier for the entry)
    registered organisation number
    homepage
    address
    lat
    long

https://github.com/SolidarityEconomyAssociation/open-data-and-maps/issues/178

**Comment by sunnydean** [comment]
Related issue:
https://github.com/SolidarityEconomyAssociation/open-data-and-maps/issues/183

**Comment by ColmMassey** [comment]
We are now publishing data from ICA-Youth. Some of those co-ops have .coop domains and thus are connected to or are the sameas a co-op in the DotCoop data set.
