### ISSUE TITLE
Collect richer data from Coops-UK 2019

### ISSUE THREAD

**Issue by sunnydean** [p6data-coop/ise-linked-open-data#185]
We have currently uploaded the latest data at https://w3id.solidarityeconomy.coop/coops-uk/test2019/ . We had issues due to multiple entries for the same outlet but with a different phone number. I have written a script to remove the duplicates, but we need to use the phone numbers. We have to combine the phone numbers into one field (as we do for websites in dotcoop) and we will have successfully updated the data.
Also need to collect more data from the csvs.
https://github.com/SolidarityEconomyAssociation/open-data-and-maps/issues/119

**Comment by ColmMassey** [comment]
I received an email from Co-ops UK. There is a newer data set and they have corrected the erroneous descripotions of the Outlets data. So worth a look before getting into this ticket.

"Sorry for the delayed response. 

The open data guide was misleading. Though it claimed the CUK Identifier field was the unique ID for outlet, it's actually a foreign key to the organisation dataset. 
I've just published the latest release which now includes the correct outlet id and I've also updated the open data guide.

Joe


On Wed, 11 Dec 2019 at 09:52, Colm SEA <colm@solidarityeconomy.coop> wrote:

    Hiya,

    Colm from SEA here. We are doing some more work on open data and taking a look at the latest open data set you published, q3 2019.

    In the guide, re outlets, you say there is a CUK Outlet ID for each outlet. I can't see that. There are also lots of duplicates. E.g. R000001 | Co-operative Group Limited | The Co-operative Food - Tiree |
    appears 4 times.

    Can you shed any light?
    In solidarity,

"

**Comment by ColmMassey** [comment]
This is turning into a large issue, as it could also include looking at a more generic way of handling outlets, how they can be displayed in a distinct manner, etc.

**Comment by ColmMassey** [comment]
At the moment, the only way to interpret they are outlets is by the fact that it has a different (longer) type of URI. We should not be infering things from the structure of the uri. We need to create a new field to indicate an inititative is an outlet/branch/whatever of an other inititiative and then provide a link back to that parent.
