### ISSUE TITLE
Tidy up repository and servers

### ISSUE THREAD

**Issue by sunnydean** [p6data-coop/ise-linked-open-data#186]
Tidying up repository and make one server a production one and one a development one

**Comment by wu-lee** [comment]
I'm going to split this ticket to cover the various parts of the job  (as I see it). Some of this has been done already. Comments welcome.
- Make the map-app a self-contained NPM package in its own repository, for ease of re-use #192
- Convert the linked-data sausage factory into a self-contained application in its own repository #193
- Identify the components needed to deploy a mini-website server / SPARQL data endpoint #194
- Propose how to separate development from live deployments of SEA's websites (or at least the map websites) #195
- execute this proposal #196

**Comment by wu-lee** [comment]
Closing as redundant - see sub tickets
