### ISSUE TITLE
Display a status message when a data set is being loaded.

### ISSUE THREAD

**Issue by ColmMassey** [p6data-coop/ise-linked-open-data#187]
When loading large datasets or on slow connections it is very helpful to have a status message indicating that a data set is being loaded and any relevant info available, like its address.

**Comment by ColmMassey** [comment]
Do we have any timeouts in place for this loading? Is that easy to put in? What would we do if it did timeout?

**Comment by sunnydean** [comment]
Made a loading bar here:
https://dev.playground.solidarityeconomy.coop/

It will display a short timeout message if there is an error:
Error occurred while loading data

**Comment by ColmMassey** [comment]
Nice. Can we reduce the size of the circle a little? It gets clipped on my phone. 
We may need to put it someone else when we have multiple databases, but we can close for now.

**Comment by sunnydean** [comment]
Updated the size

**Comment by sunnydean** [comment]
at http://dev.playground.solidarityeconomy.coop/ @ColmMassey
