### ISSUE TITLE
Hide map marker option.

### ISSUE THREAD

**Issue by ColmMassey** [p6data-coop/ise-linked-open-data#188]
Create an option to disable visualisation of map markers based on directory category and search options string matches.

1) Beside the search string box, provide a tickbox. When it is not ticked, initiatives which don't match the search criteria no longer have their icons displayed on the map.

2) For each category displayed on the Directory panel, provide a tickbox. If the tick is disabled then the initiatives in this category would not be displayed in the directory, or as icons on the map.

**Comment by ColmMassey** [comment]
Is there an addreess where I can review this feature yet? @dtmakm27?

**Comment by sunnydean** [comment]
Here: http://dev.playground.solidarityeconomy.coop/

**Comment by sunnydean** [comment]
and for a smaller map this is how it looks: https://dev.oxford.solidarityeconomy.coop/

**Comment by sunnydean** [comment]
Markers are hidden whenever you search or select filters

**Comment by ColmMassey** [comment]
Works as expected.
