### ISSUE TITLE
Convert the linked-data sausage factory into a self-contained application in its own repository

### ISSUE THREAD

**Issue by wu-lee** [p6data-coop/ise-linked-open-data#193]

**Comment by ColmMassey** [comment]
This is now in the new repository [open-data](https://github.com/SolidarityEconomyAssociation/open-data)

**Comment by ColmMassey** [comment]
I think someone @wu-lee @dtmakm27 said that there was still something to do to make this usable? Something to do with a token? Or was it just that the ReadMe needed to be updated?

**Comment by sunnydean** [comment]
need to update documentation *

**Comment by ColmMassey** [comment]
Shall we create a new issue in the new repository, to redo the documentation for building a database, and close this one? It can wait until March.

**Comment by sunnydean** [comment]
Yes, I'll write up something short for now but will make a proper one later
We can close this one

**Comment by wu-lee** [comment]
I tried to use the `open-data` repo and it seems to be missing some things. I don't know if there's a new ticket for that but adding that here. @dtmakm27 perhaps you can make sure this gets copied into the right place?

- [x] it's not accessible to members of the developers group, so I can't modify it.
- [ ] the documentation needs updating, as it is incomplete/incorrect in places
- [x] it now needs an API key before you can build anything (that should probably go into an encrypted store?)
Possibly some other things, @dtmakm27, you mentioned a CSV file?

**Comment by ColmMassey** [comment]
>     * it now needs an API key before you can build anything (that should probably go into an encrypted store?)

Why would one need an API key?

**Comment by wu-lee** [comment]
> Why would one need an API key?

I'm not sure, seems to be something to do with the OpenCage. Running this:

    make -f ../../tools/se_open_data/makefiles/generate.mk edition=experimental

Fails with:
```
tools/se_open_data/lib/se_open_data/csv/open_cage_standard.rb:27:
in `read': No such file or directory @ rb_sysopen - ../APIs/OpenCageKey.txt (Errno::ENOENT)
```

**Comment by ColmMassey** [comment]
> seems to be something to do with the OpenCage
Of course. Essential for generating long/lats for no UK Postcode available. 
@dtmakm27, it should be an option as not always needed.

**Comment by wu-lee** [comment]
Dean's given me the missing files, so I can use this now. However these may need to be committed somewhere suitable (i.e. maybe not here), will look into it.

**Comment by wu-lee** [comment]
Note, the OpenCage.txt API key now committed in encrypted form here:

https://github.com/SolidarityEconomyAssociation/password-store/blob/master/OpenCageKey.txt.gpg

I propose the ruby script grab it from there by shelling out to the `pass` command as appropriate?  This however requires that the `pass` command has been set up correctly beforehand and the user has a passphrase to a GPG key with access.

**Comment by sunnydean** [comment]
I have put in the required documentation. 

There are some files we are passing on from person to person for now. I have put that in the documentation as well but it would be best to include a person to email in this sentence:

"To get these files request them from the current developers or the project manager."

Should we put in your email @ColmMassey 

After we decide this we can close this issue

**Comment by ColmMassey** [comment]
Let's create an alias for the moment lod@solidarityeconomy.coop?
Put any further documentation updates you think are required in [here](https://github.com/SolidarityEconomyAssociation/open-data/issues/7)

**Comment by ColmMassey** [comment]
lod@solidarityeconomy.coop now redirects to all of us for the moment.

**Comment by ColmMassey** [comment]
Actually best to stay within Github and use Issues to communicate. Updated docs [here](https://github.com/SolidarityEconomyAssociation/open-data/commit/11a7362546e509b3d179581b1fff6f414b14fc45#diff-e70100059cc3a7376740bbe9751a082e) to explain.
