### ISSUE TITLE
Is the "Virtuoso adapter requires the ODBC extension to be loaded." for MacOsX is resolved ?

### ISSUE THREAD

**Issue by cfrancois7** [p6data-coop/ise-linked-open-data#23]
I got the same error on my MacOsX. Someone has resolved the problem ?
See [here](https://github.com/p6data-coop/ise-linked-open-data/wiki/OntoWiki-Installation-Mac-OS) for the reference.

**Comment by matt-wallis** [comment]
Sorry. I don't know if anyone resolved that problem. I am no longer attempting to run OntoWiki on Mac/OsX, but using linux instead.  
I think my record of what I had to do to [run OntoWiki on Ubuntu](https://github.com/p6data-coop/ise-linked-open-data/wiki/OntoWiki-Installation-Ubuntu) are reasonably reliable.
