### ISSUE TITLE
Leaflet's global L variable sometimes not defined

### ISSUE THREAD

**Issue by matt-wallis** [p6data-coop/ise-linked-open-data#24]
Occasionally, the map-app fails to load because Leaflet's global variable L is not defined.
The source code for map-app should never use L directly, but use the variable from the define function, with leaflet loaded as an AMD module.
The most likely source is therefore the awesomemarkers plugin.

**Comment by matt-wallis** [comment]
Consider loading this leaflet stuff using `<script>` tags in html. I think that will ensure they are loaded before continuing. See https://leafletjs.com/examples/quick-start/ for and example.

While we at it, AwesomeMarkers seem to now be better maintained here:
https://github.com/sigma-geosistemas/Leaflet.awesome-markers
Consider switching to this.

And let's use the latest version of Leaflet!

**Comment by matt-wallis** [comment]
Also so a possible fix here: https://github.com/lvoogdt/Leaflet.awesome-markers/issues/57

**Comment by matt-wallis** [comment]
https://github.com/SolidarityEconomyAssociation/open-data-and-maps/commit/10733e7d2fa2ff7078afa09c41028645933042fe follows advice in lvoogdt/Leaflet.awesome-markers#57

Fingers crossed it's a fix. Time will tell for this intermittent problem.

**Comment by matt-wallis** [comment]
https://github.com/SolidarityEconomyAssociation/open-data-and-maps/commit/10733e7d2fa2ff7078afa09c41028645933042fe  may have fixed the issue with regard to awesome markers, but marker cluster is still causing problems.

**Comment by matt-wallis** [comment]
Problem not seen since commit https://github.com/SolidarityEconomyAssociation/open-data-and-maps/commit/c0418e63dad52d51032bc23e4fb9ed0e1f25fc41
Closing -reopen if it reappears.

**Comment by matt-wallis** [comment]
Aaargh! Following an update to leaflet.markercluster 1.3.0, the problem is back. Ugh!
I've asked about it: https://github.com/Leaflet/Leaflet.markercluster/issues/441#issuecomment-393532325
Thanks to Jon for spotting it.

**Comment by novakand** [comment]
The angular application does not start when importing LeafletMarkercluster,
import {MarkerClusterGroup} from "leaflet.markercluster" error. ReferenceError: L is not defined

I need to connect the maps API via the script download: https://unpkg.com/leaflet@1.3.4/dist/leaflet.js
Next, I need to initialize Markercluster.
  Tell me how to be?
