### ISSUE TITLE
Make map-app work well on all devices

### ISSUE THREAD

**Issue by matt-wallis** [p6data-coop/ise-linked-open-data#25]
The text is too small. 
See [Leaflet notes on mobiles](http://leafletjs.com/examples/mobile/).
See [Google notes on Responsive Design](https://developers.google.com/web/fundamentals/design-and-ui/responsive/).

---
#### TaslJuggler
TJ: effort 2d
TJ: depends-on #73 
TJ: depends-on #77

**Comment by matt-wallis** [comment]
The context menus are somewhat small and fiddly on mobile. The links are difficult to hit!

- [ ] Fix the fiddly context menus

**Comment by ColmMassey** [comment]
Has this been addresses now by using the new libraries?

**Comment by matt-wallis** [comment]
> Has this been addresses now by using the new libraries?

I think so. The remaining issue that I'm aware is covered by #77. So closing this.
