### ISSUE TITLE
Display Co-ops UK 2017 data on map-app

### ISSUE THREAD

**Issue by matt-wallis** [p6data-coop/ise-linked-open-data#28]
Maybe we also want to use this as an opportunity to allow the map-app to display data from different sources:
- 2016 data
- 2017 data

**Comment by matt-wallis** [comment]
@ColmMassey - you can now see the [Coops UK 2017 data on a map](https://maps.solidarityeconomy.coop/coops-uk/2017/)

There's more to do, but this is a significant milestone. :-)

**Comment by ColmMassey** [comment]
Is this not closable. It's as feature complete as the old map. Extensions can have new tickets?

**Comment by matt-wallis** [comment]
> Is this not closable.

@ColmMassey, I _think_ that's one of my favourite typos - mean _now_, but type _not_. :-) Yes?

Somethink not yet implemented, but mentioned in the original body of the issue is the ability to choose which data to load into the map - I've created a new issue #63 for that.

**Comment by ColmMassey** [comment]
I think now or not both work.
