### ISSUE TITLE
DCAP-SSE uses vcard:street-addressglobal - not in vcard vocab

### ISSUE THREAD

**Issue by matt-wallis** [p6data-coop/ise-linked-open-data#3]
The Address class of  [DCAP-SSE](http://purl.org/essglobal/wiki) uses http://www.w3.org/2006/vcard/ns#street-addressglobal, whereas the [VCARD spec](https://www.w3.org/TR/vcard-rdf/#Delivery_Addressing_Properties) uses http://www.w3.org/2006/vcard/ns#street-address. Note that **global** is appended to the one used in DCAP-SSE.

Is this intentional (how could it be?) a typo or cut & paste error?

**Comment by marianamalta** [comment]
It can be a typo or a very stupid error. I note that this work has never been validated. You are the validators if you decide to use the model. So this is already so good that you are paying attention to details and trying to understand! I will come back asap with a comment, i need time to analyse the question.

**Comment by matt-wallis** [comment]
Closing as this issue has been moved to a more appropriate repository. Please go there for further comments etc:
https://github.com/essglobal-linked-open-data/map-sse/issues/23
