### ISSUE TITLE
Update map-app README

### ISSUE THREAD

**Issue by matt-wallis** [p6data-coop/ise-linked-open-data#32]
The current [README](https://github.com/SolidarityEconomyAssociation/open-data-and-maps/blob/master/map-app/README.md) is really about the co-ops UK 2016 data.

We need a new one for 2017 data.

This README is what you see when you click the `About` button on the map-app application. If the 2016 README is renamed, then the map-app link in the javascript needs to be changed to follow this. And similarly for a 2017 version of the map-app.

Of course, if the map-app is modified to allow the display of either 2016 or 2017 data, then some thinking needs to be done about whether to have a separate README, or to modify the README to reflect that either data set may be displayed.

---
#### Project planning info
This will be used as input for TaskJuggler ... to create project plans.
Lines beginning with `TJ: ` are machine-readable - caution needed when editing!

TJ: effort 3d

**Comment by matt-wallis** [comment]
It would probably be better if the `About` button on the map-app launched a dialog which displayed text that was relevant to the specific variant (see #67) of the map.
This doesn't take away from the fact that the README needs updating.

**Comment by ColmMassey** [comment]
[This](https://github.com/SolidarityEconomyAssociation/open-data-and-maps/blob/development/map-app/README.md) readme has now been updated.
