### ISSUE TITLE
Generate LOD from 'standard' set of spreadsheets

### ISSUE THREAD

**Issue by matt-wallis** [p6data-coop/ise-linked-open-data#37]
If we have a mechanism for generating LOD from a standard set of spreadsheets, then the work of creating a new dataset becomes the work of populating this standard set of spreadsheets.
Of course, we first need to do the work to check that this approach is feasible, and to design the details of the process.  

The benefits of this approach are:
- we re-use the same software tools to convert the standard spreadsheets into LOD
- creating the standard spreadsheets can be done by anyone who can create a spreadsheet - no technical knowledge of LOD is required
- the correspondence between the spreadsheets and the generated LOD should be a useful educational aid for those who are familiar with tabulated data, but not with LOD.

**Comment by ColmMassey** [comment]
When you spreadsheet, do we really mean accessing an ods or xls via an api, or reading a csv exported from a spreadsheet app?

It seems highly desirable to have the data entry for these databases via a human readable spreadsheet form. Lowers the entry bar considerably.

**Comment by ColmMassey** [comment]
Would we be modifying existing software that does this already, or starting from scratch?

**Comment by matt-wallis** [comment]
I mean reading from a CSV - all spreadsheet programs can produce CSV. It is, if you like,  standard interchange format for tabular data. Yes - lowering the bar is a very good thing.

> Would we be modifying existing software that does this already, or starting from scratch?

It is modifying existing software - splitting the existing process into two separate tasks:
1. Read in co-ops UK CSV (already done) and write it out in our standard CSV (new).
2. Read our standard CSV (a modification to the code that currently reads co-ops UK CSV) and generate LOD (existing software)

**Comment by matt-wallis** [comment]
This is implemented by the ruby script [standard-csv-to-rdf.rb](https://github.com/SolidarityEconomyAssociation/open-data-and-maps/blob/master/data/tools/se_open_data/bin/standard-csv-to-rdf.rb), which uses the [SeOpenData library](https://github.com/SolidarityEconomyAssociation/open-data-and-maps/tree/master/data/tools/se_open_data/lib/se_open_data).

The standard is currently very minimal (it is enough to generate the RDF that we created for the 2016 co-ops UK data). It is defined in [standard.rb](https://github.com/SolidarityEconomyAssociation/open-data-and-maps/blob/master/data/tools/se_open_data/lib/se_open_data/csv/standard.rb).
