### ISSUE TITLE
Allow exact geo-locations to be used (as alternative to postcodes)

### ISSUE THREAD

**Issue by matt-wallis** [p6data-coop/ise-linked-open-data#38]
With the 2016 Co-ops UK data, all geo-location was done via the postcode. This was a pragmatic choice as that was the only information available. But we want to allow the exact lat/lon to be used when these are available.
- [x] Design how to incorporate this into our generated LOD
- [ ] get the map-app to use the exact location in preference to postcode

### TaskJuggler
TJ: effort 3h

**Comment by matt-wallis** [comment]
Our [standard CSV](https://github.com/SolidarityEconomyAssociation/open-data-and-maps/blob/master/data/tools/se_open_data/lib/se_open_data/csv/standard.rb) now allows Lat and Long to be added explicitly. Here's an extract from that file:
```
  # latitude and longitude are for the exact geolocation of the SSE initiative,
  # if it is known. 
  # If only a postcode is known, see geocontainer, below.
  latitude: "Latitude",
  longitude: "Longitude",

  # Often, we don't know the exact lat/long of an SSE initiative, but we know about 
  # a geographic container which has a known lat/long.
  # The most common example of this is the postcode as a geographic container.
  #
  # Note that the utility `bin/csv/standard/add-postcode-lat-long.rb` will populate
  # these 3 fields based on the value of the Postcode, so don't do it manually!
  # This is used, for example, in the toolchain for generating the co-ops-uk 2017 RDF.
  geocontainer: "Geo Container",
  geocontainer_lat: "Geo Container Latitude",
  geocontainer_lon: "Geo Container Longitide"
```
The specific requirement of this issue is also mentioned in #35.

**Comment by matt-wallis** [comment]
In order to
>  get the map-app to use the exact location in preference to postcode

we first need to check if that exact location is being passed to the map-app.
Currently, the map-app is given data in simplified json format from the web server.
By 'simplified', I mean that it is not the raw JSON-LD that comes from the SPARQL query.
Perhaps the map-app should be receiving the raw JSON-LD?
The reason for doing this would be to 'cut out the middle man', where in this case, the 'middle man' is the PHP script on the web server that converts the JDON-LD into 'simplified' json.

**Comment by ColmMassey** [comment]
@matt-wallis How big a job remains to complete this Issue?
Also, where is the latest spec for the csv format that is now supported?

**Comment by matt-wallis** [comment]
> where is the latest spec for the csv format that is now supported?

@ColmMassey - Here is the [ruby definition of SeOpenData::CSV::Standard::V1](https://github.com/SolidarityEconomyAssociation/open-data-and-maps/blob/master/data/tools/se_open_data/lib/se_open_data/csv/standard.rb).

To interpret what this means, view the above link. Here's an extract starting at line 20:
```
          id: "Identifier",
          name: "Name",
          description: "Description",
          # The allowed values for legal_form are taken from essglobal.
          legal_forms: "Legal Forms",
          street_address: "Street Address",
```
So, the standard CSV column headings include "Identifier", "Name", Description", "Legal forms", etc, plus all the other ones that are contained in the ruby, but not listed above. 

The comments in the ruby are also important to understand how this standard is used in practice.

Typically, there is a step to pre-process any CSV that we are given, and this pre-processing varies fro one dataset to another. For example, here's the [pre-processor for newcastle-mapjam](https://github.com/SolidarityEconomyAssociation/open-data-and-maps/blob/master/data/newcastle-pilot/2018-10-mapjam/converter.rb). Looking at line 63:
```
  def id
    raise(SeOpenData::Exception::IgnoreCsvRow, "\"Name\" column is empty") unless name

    name.gsub(/[^0-9a-z]/i, '')
  end
```
we see here the method used to create the `id` field (which has the column heading "Identifier" in the `SeOpenData::CSV::Standard::V1` format). What this does it to take the name of the initiative from the original CSV (the one we get before pre-processing), and remove everything from it that is neither a number nor a letter.

**Comment by ColmMassey** [comment]
Is this now working Joe? I's close it unless there is something left to complete.

**Comment by joebillings** [comment]
Yes, sorry! https://dotcoop.solidarityeconomy.coop/
