### ISSUE TITLE
map-app should make clear when approx geo-locations are used

### ISSUE THREAD

**Issue by matt-wallis** [p6data-coop/ise-linked-open-data#40]
When we use postcode units, for example, as the geo-location, the point shown on the map is rarely the exact location of the thing that is being located. The size of the error is proportional to the size of the postcode unit. It can be big in rural areas. There's some info [here on postcode areas](https://www.quora.com/Whats-the-average-area-sq-km-contained-by-a-full-postcode-in-the-UK) stating that they can be as big as 0.5㎢.

So the problem for the user is that the icons on the map are positioned at an exact geo-location, but that may be a significant distance (e.g. if you're trying to find somewhere on the ground) from the actual location.

Related to this is that postcode boundary information is available, but it is not freely, openly available.

**Comment by joebillings** [comment]
We could potentially show a ring/area around markers in a similar way to the way that clusters display the area of the markers they represent.
