### ISSUE TITLE
Decide whether to generate co-ops uk 2017 data using standard spreadsheets

### ISSUE THREAD

**Issue by matt-wallis** [p6data-coop/ise-linked-open-data#41]
By 'standard spreadsheets', we mean what is referred to in #37.

If we plan to use this approach in the future (for the other data sets we plan to publish), then it makes sense to use the co-ops UK 2017 data as a proving ground for the approach.

**Comment by matt-wallis** [comment]
Added pressing label as making this decision affects what is to be done in the very near future

**Comment by ColmMassey** [comment]
I think main question is how big  job this is?

**Comment by matt-wallis** [comment]
> I think main question is how big job this is?

If we agree that we should address issue #37 (and I strongly think we should), then the extra work involved in converting coops UK data to a standard CSV format is not big. But it does mean that #37 needs to have the milestone https://github.com/SolidarityEconomyAssociation/open-data-and-maps/milestones/1

**Comment by ColmMassey** [comment]
I agree.

**Comment by matt-wallis** [comment]
Closing as we have now decided to generate the co-ops UK LOD from a standard spreadsheet. This means that the milestone for issue #37 has changed.
