### ISSUE TITLE
Include photos in our LOD

### ISSUE THREAD

**Issue by matt-wallis** [p6data-coop/ise-linked-open-data#42]
We want the gathering of information about SE initiatives to be a social process, with lots of people involved. This information is then used to create Open Data. 
Let's allow photos to be part of that social process. A photo could be of the shop front of an SE, but of course the sky is the limit!
Wouldn't it be great for people to be able to view these photos via the map-app?

This idea is inspired by the [Tranquil City Exeter](https://tranquilcity.co.uk/2017/06/13/tranquil-city-exeter/) project brought to my attention by @SEAKatDarling.

Technically, this is quite straightforward, especially when photos are taken on GPS-enabled devices and published on the web (e.g. via Instagram), where the photo has a URL. The only remaining bit of glue is that in order to submit the photo for inclusion on a map, you've got to say which SE initiative the photo is about.

As a side effect, the lat/long of a photo may provide a more accurate geo-location than, say, the postcode. See related issue #38.

Perhaps this could also form the basis for the initial collection of data about an SE initiative? More thought needed... 

Some things to investigate:
- Can we get hold of the GPS info of photos published on the web (e.g. by Instagram)? This data is originally in EXIF tags in the image file, but one would expect it to be wiped by the likes of Instagram
- (Related) How are  [Tranquil City Exeter](https://tranquilcity.co.uk/2017/06/13/tranquil-city-exeter/) getting the geo-location? 
- Should we include in our LOD hashtags for the SE initiatives? Some will already have well-known hashtags. Imagine, for example, a photo published on instragrim with two hashtags: #seopendata, and #wellknownhashtagoftheinitiative. With the appropriate feed from instragrim, we could do something with that, subject to better investigation.
- How much effort would be required to develop an app to support the feeding of info directly to us from people's mobile devices? Is that even necessary, or are there other alternatives?

**Comment by joebillings** [comment]
[Updated link for Tranquil City](https://www.exetercityfutures.com/tranquil-city-exeter/)
