### ISSUE TITLE
Deployment overwrites too many files

### ISSUE THREAD

**Issue by matt-wallis** [p6data-coop/ise-linked-open-data#46]
Consider this: 
```
bombyx:~/SEA/open-data-and-maps/data/co-ops-uk/2017-06$ make deploy edition=test
ssh parecco 'cd public_html/subdomains/solidarityeconomics.org/data/ && mkdir -p doc/experimental/test/'
rsync -avz  --delete generated-data/test/experimental/test/ parecco:public_html/subdomains/solidarityeconomics.org/data/doc/experimental/test/
```
(where bombyx:~/SEA/open-data-and-maps is a clone of this repo).

After the deployment, looking at the location on the server to which the data has been deployed:
```
pareccoc@nlss8 [~/public_html/subdomains/solidarityeconomics.org/data/doc]# ls experimental/test
co-ops-uk2017/  co-ops-uk2017.html  co-ops-uk2017.rdf  co-ops-uk2017.ttl  co-ops-uk2017_all.rdf  co-ops-uk2017_all.ttl
```
If there was anything in the `experimental/test` directory before the deployment, it will have been deleted. In particular, this 2017 data has overwritten the 2016 data. That's not what we want!

**Comment by matt-wallis** [comment]
Ideally, the solution to this should leave the 2016 version of [`generate-triples.rb`](https://github.com/SolidarityEconomyAssociation/open-data-and-maps/blob/master/data/co-ops-uk/2016-06/generate-triples.rb) unchanged.

If we look at the deployment path `parecco:public_html/subdomains/solidarityeconomics.org/data/doc/experimental/test/`, it can be broken down as follows:
- `parecco:public_html/subdomains/solidarityeconomics.org/data` corresponds to the subdomain `data` on the domain `solidarityeconomics.org`
- `doc` is where documents go
- `experimental` is a reference to the fact that the co-ops UK 2016 LOD was experimental
- `test` is a variant of the dataset.

This path structure does not server us well as we move on to create the co-ops UK 2017 data, the issue reported here is a symptom of that. The suggested fix is to start by redesigning the path. NB there may well be an interaction between this document path and the re-design of URIs (see #26).

**Comment by matt-wallis** [comment]
This is still a problem, although reduced in size, in that the data generated by the editions `test2017` and `final` are written to the same location on our server:
```
bombyx:~/SEA/open-data-and-maps/data/co-ops-uk/2017-06$ make --dry-run edition=final deploy
ssh ise-0-matt 'cd /var/www/html/data1.solidarityeconomy.coop/ && mkdir -p coops-uk/2017/'
rsync -avz  --delete generated-data/final/www/doc/ ise-0-matt:/var/www/html/data1.solidarityeconomy.coop/coops-uk/2017/
ssh ise-0-matt 'cd /var/www/html/data1.solidarityeconomy.coop/ && mkdir -p css/coops-uk/2017/'
rsync -avz  --delete generated-data/final/www/css/ ise-0-matt:/var/www/html/data1.solidarityeconomy.coop/css/coops-uk/2017/

bombyx:~/SEA/open-data-and-maps/data/co-ops-uk/2017-06$ make --dry-run edition=test2017 deploy
ssh ise-0-matt 'cd /var/www/html/data1.solidarityeconomy.coop/ && mkdir -p coops-uk/2017/'
rsync -avz  --delete generated-data/test2017/www/doc/ ise-0-matt:/var/www/html/data1.solidarityeconomy.coop/coops-uk/2017/
ssh ise-0-matt 'cd /var/www/html/data1.solidarityeconomy.coop/ && mkdir -p css/coops-uk/2017/'
rsync -avz  --delete generated-data/test2017/www/css/ ise-0-matt:/var/www/html/data1.solidarityeconomy.coop/css/coops-uk/2017/
``` 
But, this problem can be lived with easily, so chaning the milestone for this issue.

**Comment by matt-wallis** [comment]
As a result of the [9adeffa commit](https://github.com/SolidarityEconomyAssociation/open-data-and-maps/commit/9adeffa075a0fde9f9fe01c578a88d629e6296e7), the rsync uses the --delete flag only for the final edition:
```
bombyx:~/SEA/open-data-and-maps/data/co-ops-uk/2017-06$ make -n edition=test2017 deploy
ssh ise-0-matt 'cd /var/www/html/data1.solidarityeconomy.coop/ && mkdir -p coops-uk/2017/'
rsync -avz   generated-data/test2017/www/doc/ ise-0-matt:/var/www/html/data1.solidarityeconomy.coop/coops-uk/2017/
ssh ise-0-matt 'cd /var/www/html/data1.solidarityeconomy.coop/ && mkdir -p css/coops-uk/2017/'
rsync -avz   generated-data/test2017/www/css/ ise-0-matt:/var/www/html/data1.solidarityeconomy.coop/css/coops-uk/2017/

bombyx:~/SEA/open-data-and-maps/data/co-ops-uk/2017-06$ make -n edition=final deploy
ssh ise-0-matt 'cd /var/www/html/data1.solidarityeconomy.coop/ && mkdir -p coops-uk/2017/'
rsync -avz  --delete generated-data/final/www/doc/ ise-0-matt:/var/www/html/data1.solidarityeconomy.coop/coops-uk/2017/
ssh ise-0-matt 'cd /var/www/html/data1.solidarityeconomy.coop/ && mkdir -p css/coops-uk/2017/'
rsync -avz  --delete generated-data/final/www/css/ ise-0-matt:/var/www/html/data1.solidarityeconomy.coop/css/coops-uk/2017/
```
This lessens the risk of damage.

**Comment by ColmMassey** [comment]
We will look at this in tidy up at end of sept.
