### ISSUE TITLE
Find out about parseType=Resource and blank nodes

### ISSUE THREAD

**Issue by matt-wallis** [p6data-coop/ise-linked-open-data#52]
Ask on ruby-rdf mailing list how to create this: https://www.w3.org/TR/rdf-syntax-grammar/#section-Syntax-parsetype-resource
or this https://www.w3.org/TR/vcard-rdf/#Examples

Also look up W3 reference to blank nodes being a bad idea and ask about it.

**Comment by joebillings** [comment]
We want to be doing [this](https://www.w3.org/TR/vcard-rdf/#Examples) and not create specific URIs for the address/phone number
