### ISSUE TITLE
Add Pointer to Parent Co-op from Outlet Icon

### ISSUE THREAD

**Issue by ColmMassey** [p6data-coop/ise-linked-open-data#62]
If an icon in the map-app is an outlet rather than a co-op or co-op's headquarters then add a hyperlink in its pop up that selects the 'parent' icon on the map and recentres the map there. Can we also use another icon colour for outlets?

**Comment by matt-wallis** [comment]
A hyperlink in the pop-up would be quite easy to implement (on a map that was specific to coops uk).
But wouldn't it be better to model this relationship in the LOD? 
There's a comment in another issue that's very closely related: https://github.com/SolidarityEconomyAssociation/open-data-and-maps/issues/45#issuecomment-371529228

What is the use-case (or what are the use-cases) that requires a different colour for outlets? I'm not suggesting that there isn't one, but need to know what it is.

**Comment by ColmMassey** [comment]
Use case for colour difference is short term ease of use when demonstrating. It's clear what features are available on an icon before clicking it.

**Comment by ColmMassey** [comment]
Modeling the parent/outlet relationship is definitely better. It does however feel like it warrants some deeper thinking, to get it right. Should I split this into seperate features?

**Comment by matt-wallis** [comment]
> Should I split this into seperate features?

I think that's best. One for the short-term change that is meaningful only to co-ops UK data/map. The other for the longer term modelling. For the longer term modelling, ESSGLOBAL has the concept of a `Network` to which `Initiatives` can belong - not quite the same as the co-ops uk organization/outlet split, but definitely related.
