### ISSUE TITLE
map-app should allow user to choose which dataset(s) to load

### ISSUE THREAD

**Issue by matt-wallis** [p6data-coop/ise-linked-open-data#63]
As we get more datasets available, this will be come more important.

Some of the mechanism for this is already implemented. When the Linked Data is generated, a `sparql` directory is created:
```
bombyx:~/SEA/open-data-and-maps/data/co-ops-uk/2017-06$ ls generated-data/final/sparql/
default-graph-uri.txt	endpoint.txt		query.rq
```
The two `.txt` files contain URIs that are needed to form the command that's send to the sparql endpoint:
```
bombyx:~/SEA/open-data-and-maps/data/co-ops-uk/2017-06$ cat generated-data/final/sparql/*.txt
https://w3id.org/coops-uk/2017/
http://store1.solidarityeconomy.coop:8890/sparql
```
and `query.rq` is the SPARQL query itself:
``` sparql
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX vcard: <http://www.w3.org/2006/vcard/ns#>
PREFIX geo: <http://www.w3.org/2003/01/geo/wgs84_pos#>
PREFIX essglobal: <http://purl.org/solidarityeconomics/experimental/essglobal/vocab/>
PREFIX gr: <http://purl.org/goodrelations/v1#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX ospostcode: <http://data.ordnancesurvey.co.uk/id/postcodeunit/>
PREFIX rov: <http://www.w3.org/ns/regorg#>
PREFIX osspatialrelations: <http://data.ordnancesurvey.co.uk/ontology/spatialrelations/>
PREFIX : <https://w3id.org/coops-uk/2017/>

SELECT ?name ?uri ?within ?lat ?lng ?www ?regorg
WHERE {
	?uri rdf:type essglobal:SSEInitiative .
	?uri gr:name ?name .
	OPTIONAL { ?uri foaf:homepage ?www . }
	?uri essglobal:hasAddress ?addr .
	OPTIONAL { ?uri rov:hasRegisteredOrganization ?regorg . }
	?addr osspatialrelations:within ?within .
	?within geo:lat ?lat.
	?within geo:long ?lng.
}
LIMIT 14662
```
Together, these three files are sufficient to provide access to one dataset. To procide access to two datasets, we just need two of these directories. This can be seen in the source for the map-app:
```
bombyx:~/SEA/open-data-and-maps/data/co-ops-uk/2017-06$ ls ~/SEA/open-data-and-maps/map-app/www/services/coops-uk*
/Users/matt/SEA/open-data-and-maps/map-app/www/services/coops-uk2016:
default-graph-uri.txt	endpoint.txt		query.rq

/Users/matt/SEA/open-data-and-maps/map-app/www/services/coops-uk2017:
default-graph-uri.txt	endpoint.txt		query.rq
```
These files get deployed to the web server which serves the map-app application. 

What remains to be done?

- [x] Add a parameter to the command sent from the map-app in the browser to the web server to ask for a particular dataset
- [ ] Code up a mechanism in the map-app to allow the user to choose a dataset.

**Comment by ColmMassey** [comment]
@wu-lee Was doing some tidying and noticed this ticket. Thought I'd draw it to your attendtion in case there was anything interesting in there. Can you close it after taking a look, if you agree it is now superfluous.

**Comment by ColmMassey** [comment]
@wu-lee Which Issue do you thik superceeds this one?
https://github.com/SolidarityEconomyAssociation/sea-map/issues/1 ?

**Comment by wu-lee** [comment]
Sorry, didn't see the earlier comment.

I think this is superflous, right @dtmakm27? We can support multiple datasets, and switch between them.

I don't know if SolidarityEconomyAssociation/sea-map#1 supercedes this exactly, it's more about reading configuration parameters from the URL and overriding the defaults in `config.json`. Although this could select a dataset - at least in principle.

What seems a more natural heir is the one about properly supporting more than two datasets, #184 I think. At the moment we combine two using a method which doesn't scale to more.

**Comment by ColmMassey** [comment]
>I don't know if SolidarityEconomyAssociation/sea-map#1 supercedes this exactly,

You are right that is different.
Good handling of sameas' will make better use of multiple data sources but it is not the same as being able to specify what datasets to use.
At the moment we support the option of choosing between one of all of the preassigned databases, but a user couldn't just point it to a compatible triplestore/sparql endpoint and display whatever compatible data it found there, which I think was the intent.

**Comment by ColmMassey** [comment]
But this is not a requirement right now, so we can leave it open but not scheduled.
