### ISSUE TITLE
Make dataset icons configurable

### ISSUE THREAD

**Issue by matt-wallis** [p6data-coop/ise-linked-open-data#69]
Currently, we use different icons (from font-awesome) for each dataset. These are hard-coded:
```
$ grep -r --include '*.js' 'globe' www/app
www/app/presenter/map.js:		var icon = initiative.dataset == 'dotcoop' ? 'globe' : 'certificate';
```
Better to configure them via `variants/<variant>/config.json`

But we want to use icons for more than just to distinguish between 2 datasets. In fact, we may *not* want to use them to distinguish between datasets at all! Instead, we want to use icons to distinguish between *types of initiative*.
That begs some big questions:
- What to we mean by a *type of initiative*?
Clearly, there are some informal requirements: I want to see cafés with a 'cup' icon, etc.
But how do we generalise this? What do we need in our data to make this work?
- Should we encode icons into our LOD?
Pros: It would provide a mechanism for hand-picking icons for each initiative
Cons: We'd need to hand pick icons for each initiative!
Perhaps there are different layers that can influence the icon:
  - The icon defined in the initiative,
  - Some heuristics to select an icon based on other data fields,
  - Some UI control over which icons are used,
  - Configuration of a map variant

There's quite a bit of work here, to select a strategy and choose how much of it to implement in the short term. 
---
#### TaskJuggler
TJ: effort 3d

**Comment by ColmMassey** [comment]
Is there some improved configurabilty work that can be done before decisions are made about what 'hooks' we wish to use to decide on what icons to display? Or do we need to wait until we'd have discussions with our 'clients'?

**Comment by matt-wallis** [comment]
> Is there some improved configurabilty work that can be done before decisions are made...

I can't think of any. The next step is to analyse requirements (from 'clients' and by looking more deeply into what is outlined above) and work out a solution. Did you have something specific in mind?

**Comment by ColmMassey** [comment]
Needs some deeper thinking, with clients, both internal and external.
