### ISSUE TITLE
Create 'about' information in the map

### ISSUE THREAD

**Issue by matt-wallis** [p6data-coop/ise-linked-open-data#74]
We want an `About` button on the map that provides information about this version of the map.
This needs to be configurable, as each map will be different.
In the original map app, the `About` button followed a link to the `README.md` for the repo. This is both out of date (see #32) and not configurable.
We need to make use of the CSS framework (see #73) to do this.

---
#### TaskJuggler
TJ: effort 1d
TJ: depends-on #73

**Comment by matt-wallis** [comment]
Things have moved on a bit ... the About info will now be put in the sidebar.

**Comment by matt-wallis** [comment]
In a soon-to-be committed change, we're using [d3-fetch](https://github.com/d3/d3-fetch) to load an HTML fragment from `configuration/about.html`.

This has the side effect that **we now need to include a polyfill for the fetch API**, since support for the fetch API is sketchy from the likes of Microsoft IE. The [github fetch polyfill](https://github.com/github/fetch) seems to be [well recommended](https://ourcodeworld.com/articles/read/625/top-5-best-javascript-polyfills-for-the-fetch-api).

**Comment by matt-wallis** [comment]
The about info for the NewBridge map could be based on this:
https://docs.google.com/document/d/129rzZfdClTwKGVIB7HGVZVui0tDO2m-h2FmAkwOuIik/edit

**Comment by ColmMassey** [comment]
We could pop it in as is to see how it looks. It needs to be 'owned' by them though.

**Comment by matt-wallis** [comment]
Implementation note: Perhaps we should use https://github.com/requirejs/text to load the about HTML.
Note the use of `!strip` to leave only what is in the `<body>` of the document.

**Comment by matt-wallis** [comment]
Note to self: that commit above was on the about-sidebar branch!
