### ISSUE TITLE
Make map popup work well on all devices

### ISSUE THREAD

**Issue by matt-wallis** [p6data-coop/ise-linked-open-data#77]
The current popup
![image](https://user-images.githubusercontent.com/15378101/42940717-5e702c1a-8b52-11e8-9d56-5394161c73ef.png)

is fiddly to use on mobiles. The links are difficult to select, and the text is small.

Consider opening a new w3.css widget (`Modal`, perhaps) as an alternative to the Leaflet marker popup.

**Comment by matt-wallis** [comment]
Instead of using a w3.css modal, could we just feed the existing popup with HTML that contains W3.CSS components (e.g. buttons, etc?)

**Comment by ColmMassey** [comment]
Visualising the initiative info in the side bar now, works well on large screen, but now on the mobile, when in map view there are no clues as to what the inititative is. As there is no mouse hover option, the only way seems to be to get out of map view to the side panel again. So perhaps if there is no hover option for the device, it should display what would be displayed when hovering?

**Comment by matt-wallis** [comment]
> Visualising the initiative info in the side bar now, works well on large screen, but now on the mobile, when in map view there are no clues as to what the inititative is. As there is no mouse hover option, the only way seems to be to get out of map view to the side panel again. So perhaps if there is no hover option for the device, it should display what would be displayed when hovering?

@ColmMassey That's a good point, and so we discussed this on our phone call today. We agreed that it might be good if, on a device with touch, and no mouse:
- a 'short' touch on an initiative's Marker causes the tooltip to be displayed.
- a 'long' touch shows that initiative in the sidebar.
Of course, this begs the question of whether these events can reliably be detected across browsers and mobile devices. There's a promising [comment in a Leaflet GitHub issue](https://github.com/Leaflet/Leaflet/issues/1542#issuecomment-15351443) that the long touch could be detected by listening to `contextmenu` events. More investigation is needed.
