### ISSUE TITLE
Separate map and data into different repositories

### ISSUE THREAD

**Issue by matt-wallis** [p6data-coop/ise-linked-open-data#79]
For historical reasons, these started in one repo, when the prototype had various dependencies between the map and the data that are (mostly) no longer present.

It would be far better if the map development was in a repository of its own. Likewise data.

TODO: Figure out which directories should go where (maybe some stay in an open-data-and-maps repo?):
```
bombyx:~/SEA/open-data-and-maps$ ls -1
3rdparty
README.md
data
docs
experiments
lib
local-oxford
map-app
presentation
rdf-server
sparql
vocab
```

TODO: Can we move a directory to a new git repo, while preserving its history?

**Comment by ColmMassey** [comment]
Reasses if this is still a good idea.

**Comment by ColmMassey** [comment]
Close this @wu-lee if you a agree that is what you have just done?

**Comment by wu-lee** [comment]
I'll check with @dtmakm27 whether we can/should split the data and sausage-factory into separate repos too, as a part of this.

**Comment by ColmMassey** [comment]
I think the original intent was what you have already done, splitting sausage factory and map-app. Seperating the data directory further into sausage-factory and data sources is a good idea. It deserves its own fresh Issue, I think.

**Comment by wu-lee** [comment]
Assigning to @dtmakm27 to create tickets(s) for data- and sausage-separation and doing the deed.

**Comment by wu-lee** [comment]
Just noticed this one still assigned to me (and Dean). @dtmakm27, @ColmMassey is this done?

**Comment by ColmMassey** [comment]
Yup. We can review if any further seperation is required some other time. https://github.com/SolidarityEconomyAssociation/open-data/issues/10
