### ISSUE TITLE
Create key for map

### ISSUE THREAD

**Issue by matt-wallis** [p6data-coop/ise-linked-open-data#83]
@SEAKatDarling commented in https://github.com/SolidarityEconomyAssociation/open-data-and-maps-outreach/issues/85#issuecomment-411002929 that the meaning of the icon colours was unclear. Very true.

The current colour scheme was a short-term aid for demonstrating aspects of the data/map to the audience at Open 2017!

For the record, the current meaning is:
- purple: initiative has website and is registered with Companies House
- blue: initiative has website
- red: initiative is registered with Companies House
- green: initiative has no website and is not registered with Companies House

This colour scheme is not particularly useful - it would be better to have a filter that allowed the user to choose to 'show me only those initiatives that have a website', etc.

In any case, we will need a key to help understand the maps.
 
The colours are implemented in the code like this:
```
bombyx:~/SEA/open-data-and-maps/map-app$ grep -r --include '*.js' markerColor www/app/
www/app/presenter/map.js:		var markerColor = (hasWww && hasReg) ? 'purple' : hasWww ? 'blue' : hasReg ? 'red' : 'green';
www/app/presenter/map.js:		var options = {icon: icon, popuptext: popuptext, hovertext: hovertext, cluster: true, markerColor: markerColor};
```

**Comment by ColmMassey** [comment]
@joebillings would we need to manually create one for each pilot? Where would we put it in the mobile mode?

**Comment by ColmMassey** [comment]
We decided we won't need a key.
