### ISSUE TITLE
Extend map search to cover more than name of initiative

### ISSUE THREAD

**Issue by matt-wallis** [p6data-coop/ise-linked-open-data#84]
@SEAKatDarling commented: https://github.com/SolidarityEconomyAssociation/open-data-and-maps-outreach/issues/85#issuecomment-411050216 that searching for 'Oxford' did not list all the initiatives in Oxford.

It would be good if there was a way to do this search. Some possibilities:

- expend the search to cover the addresses of initiatives, rather than just their names, or
- provide a mechanism for the user to say which fields they want the search to cover.

Consider also that we might want the map to zoom to Oxford when we search for it. That then becomes a different kind of search to the search on initiative name.

**Comment by ColmMassey** [comment]
I think there may also be a bug here, as both the entries that appear with the 'Oxford' search term appear under the same name...

**Comment by matt-wallis** [comment]
@ColmMassey wrote:
> I think there may also be a bug here, as both the entries that appear with the 'Oxford' search term appear under the same name...

There are two initiatives in the dotcoop dataset with the same name - one in Bristol, one in Hayes (neither in Oxfordshire :-) ). So, no bug. The original CSV data is [here](https://github.com/SolidarityEconomyAssociation/open-data-and-maps/blob/master/data/dotcoop/domains2018-04-24/original-data/Clean-UK.csv), and contains:
```
ocu.coop,Oxfordshire Credit Union,BS5 0HE,ocu.lod.coop,,,
ocu.coop,Oxfordshire Credit Union,UB3 1PE,ocu.lod.coop,,,
```

**Comment by ColmMassey** [comment]
Gotcha.

**Comment by matt-wallis** [comment]
Some thoughts on the comment by @SEAKatDarling that triggered this issue:
> Would it be possible to have a search function that allows you to search by city / first part of postcode that gives results of all co-ops in that area on the side bar, with the map moving with it?

### Adding geographic searches
It is definitely useful for the user to be able to search for a geo location by name, and have the map zoom there.
If we do this, then there *must* be a way for the user to indicate what type of search they are doing - searching for geo location, or searching for initiatives. Otherwise, the map may zoom 'automagically' when they don't want it to do so. One possible implementation is to have two search boxes. For example:
- the existing search box is used for geographic searches, and
- a new search box is added to the 'Search' sidebar for searching initiatives. In the following image, we replace the text 'Search: west' with an editable search box:
![image](https://user-images.githubusercontent.com/15378101/44784028-1ddf3400-ab84-11e8-9d1f-eb5dc0e10978.png)

With geographic searches, the map should zoom to the location regardless of whether there are any initiatives at the location. Other behaviour would be confusing to the user, violating a clear separation between geo-search and initiative-search. To implement this, we would need a gazetteer to be accessible by the application. 

It is also worth noting that the data we have about initiatives may not contain any street addresses. This is true, for example, for the current dotcoop dataset. So, to search for initiatives within Oxford, we would need to rely on some other source of geographic info (a gazetteer).

### Searching for initiatives by something other than name
It is reasonable for the user to search for initiatives based on things other than the name of the initiative. For example, the user may know the domain name of a website, and they want to find the corresponding initiative on the map.

There are (at least) two implementation options:
- The search results include initiatives with any field that matches the search string, or
- Give the user control over which fields to match (e.g. by a list of fields that can be checked via 'settings' on the Search sidebar).

**Comment by matt-wallis** [comment]
### Geo-search using GeoNames
[GeoNames](https://www.geonames.org/) provide a [web service](http://www.geonames.org/export/web-services.html), and there is a [Leaflet client library](https://github.com/consbio/Leaflet.Geonames). This is potentially brilliant to ease the implementation of a geo-search feature, and to do so in a way that works anywhere in the world.

This should be the first thing investigated if we implement geo-search.

Note that GeoNames also provide global postcode data 👍

**Comment by matt-wallis** [comment]
### Do we really want two search boxes?
The comment https://github.com/SolidarityEconomyAssociation/open-data-and-maps/issues/84#issuecomment-416933229 suggests using two search boxes. I'm not sure I like this. An alternative would be to offer a choice (in the sidebar that displays the search results) to the user as to which results she sees: geo-locations, initiatives, or both.

This could be implemented using a tab layout, maybe? Or check boxes? Cleanest way may be to use horizontal navigation from W3.css. See [W3.css example](https://www.w3schools.com/w3css/tryit.asp?filename=tryw3css_navbar_active). This is a modified version of that example, with a fragment that could be added to the fixed part of the search results sidebar (need to make sure there's no border below it):

```
<!DOCTYPE html>
<html>
<title>W3.CSS</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<body>
<div class="w3-container">

<h2>Which search results to show</h2>
<p>Add a w3-color class to let the user know which page he/she is on:</p>

<div class="w3-bar w3-border-top w3-light-grey">
  <a href="#" class="w3-bar-item w3-button w3-white">Locations</a>
  <a href="#" class="w3-bar-item w3-button">Initiatives</a>
</div>

</div>
</body>
</html>
``` 

Note that geo-searches will frequently return more than one result, so in any case, we need somewhere to display the list of results for the user to make a selection. It would make sense if this place was the search sidebar, which is another reason why it would be confusing to have 2 search boxes - i.e. the results end up in the sidebar, even if a search boxes other than the one in the sidebar were used.

**Comment by ColmMassey** [comment]
This is too broad a ticket it is part addressed by 
https://github.com/SolidarityEconomyAssociation/open-data-and-maps/issues/139
and
https://github.com/SolidarityEconomyAssociation/open-data-and-maps-outreach/issues/172
and
https://github.com/SolidarityEconomyAssociation/open-data-and-maps/issues/113
