### ISSUE TITLE
How to present on the map information about an initiative

### ISSUE THREAD

**Issue by matt-wallis** [p6data-coop/ise-linked-open-data#85]
Comment from @SEAKatDarling at https://github.com/SolidarityEconomyAssociation/open-data-and-maps-outreach/issues/85#issuecomment-411046303:

> I think we also need to think through what information goes in the pop-up boxes, and how this is presented. For example, there are clearly two (at least) distinct audiences here - one is people who want to find out what exists in their local area because they are interested potentially in supporting or connecting with others - they would probably like to have location address visible in this pop-up bit, as well as a website, and perhaps some social media links, and 'category' (e.g. food etc). For people who are developing tech apps, the links that are currently there are probably more interesting (details, which shows where the data has come from, etc). However, if I wasn't a technical person, I would find the information on the details page quite overwhelming and possibly confusing! So we need to find a good way of engaging with both audiences at the same time in this pop up box.

The current map is designed as a technical demo. So, the user-interface concentrates on features that are designed around demonstrating the benefits of LOD in a quite technical way. As pointed out above, this needs a re-think.

---
#### TaskJuggler
TJ: effort 3d
TJ: depends-on #103

**Comment by matt-wallis** [comment]
The detailed information about an initiative currently is available only via a separate tab in the browser which loads the html page which was generated along side the RDF for the initiative.

It would be better if there was detailed information about an initiative that was more integrated into the map-app itself, perhaps in the sidebar. 
This information, displayed in the sidebar, may need to vary from one map to another.
I so, this needs to be a configurable piece of the map-app.

If the details of the initiative are to be displayed in the sidebar (when the marker for the initiative is clicked, for example), then do we need the pop-up on the map at all? If we don't need the pop-up, the #77 becomes moot. Currently, the choices available vie the pop-up are all there as demonstrations of the use of LOD, rather than being of interest to general users of the map.

This feature depends on #100.

**Comment by matt-wallis** [comment]
Currently, we are not getting the full data for an initiative into the map-app. 

Here's and [example of the SPARQL query](https://github.com/SolidarityEconomyAssociation/open-data-and-maps/blob/master/map-app/www/services/dotcoop/query.rq) made by the web server, and the PHP script [getdata_using_sparql.php](https://github.com/SolidarityEconomyAssociation/open-data-and-maps/blob/master/map-app/www/services/getdata_using_sparql.php) selects only the following fields:
```
// The keys correspond to two things:
//   1. The names of the variables used in the SPARQL query (see Initiative::create_sparql_files in generate-triples.rb)
//   2. The names used in the JSON that is returned to the map-app
$keys = array("name", "uri", "within", "lat", "lng", "www", "regorg");
```
The best solution is first to fix #103

**Comment by matt-wallis** [comment]
During a chat with @ColmMassey we agreed that the initiatives sidebar needs a button that will cause the map to be zoomed and panned to the initiative(s) that are listed in the sidebar.

**Comment by ColmMassey** [comment]
@joebillings CLosing this one as obsolete I beleive
