### ISSUE TITLE
Move domain_to_homepage to the library

### ISSUE THREAD

**Issue by matt-wallis** [p6data-coop/ise-linked-open-data#87]
The function is defined in [dotcoop/domains2018-04-24/converter.rb](https://github.com/SolidarityEconomyAssociation/open-data-and-maps/blob/master/data/dotcoop/domains2018-04-24/converter.rb), but should be put into the [se_open_data library](https://github.com/SolidarityEconomyAssociation/open-data-and-maps/tree/master/data/tools/se_open_data/lib/se_open_data) for reuse ... in an ideal world.

**Comment by joebillings** [comment]
This should live in the row-reader library

**Comment by matt-wallis** [comment]
See
https://github.com/SolidarityEconomyAssociation/open-data-and-maps/blob/master/data/tools/se_open_data/lib/se_open_data/csv/row_reader.rb
