### ISSUE TITLE
Duplicate records in Newcastle pilot

### ISSUE THREAD

**Issue by ColmMassey** [p6data-coop/ise-linked-open-data#95]
More then likely raw data error, but there are two copies of Comfrey Project on the map.
Comfrey Project

Does the error repot identify and report these. If so, happy to close this straight away.

**Comment by matt-wallis** [comment]
> More then likely raw data error

Yup - there are 2 of these in the input data. They have different information in them (the `Details` column in the CSV is different), so they really need to be merged in the input data.

> Does the error repot identify and report these

No, there's no check for same name at same postcode. 

What to do? There is currently no plan to get another drop of the CSV data. But at least this issue tracks the fact that this needs to be sorted out at some point.

**Comment by ColmMassey** [comment]
No longer valid.
